name: fossflow
services:
    web:
        environment:
            - NODE_ENV=production
            - ENABLE_SERVER_STORAGE=true
            - STORAGE_PATH=/data/diagrams
            - ENABLE_GIT_BACKUP=false
        image: stnsmith/fossflow:master-4426d08@sha256:9709d727bf15c96b32860744ddeef3be693362bbea136574dc7685b61744298b
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/fossflow/data/diagrams:/data/diagrams
version: "3.7"

x-powerlab:
    store_app_id: fossflow
    title:
        en_us: FossFLOW
    tagline:
        en_us: Make beautiful isometric infrastructure diagrams
    icon: https://getumbrel.github.io/umbrel-apps-gallery/fossflow/icon.svg
    category: networking
    port_map: "8176"
    author: stan-smith
    developer: stan-smith
    source:
        catalog: umbrel-apps
        upstream_id: fossflow
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: fossflow/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:04Z"
