name: rotki
services:
    web:
        image: rotki/rotki:v1.43.0@sha256:dc4a1ac9383eddcbf28573223b0984af43a791df90cd24571d6cf19b9392bfa8
        init: true
        ports:
            - 8084:80
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/rotki/data/data:/data
            - /DATA/PowerLabAppData/rotki/data/logs:/logs
version: "3.7"

x-powerlab:
    store_app_id: rotki
    title:
        en_us: rotki
    tagline:
        en_us: Portfolio tracking, analytics, accounting and tax reporting
    icon: https://getumbrel.github.io/umbrel-apps-gallery/rotki/icon.svg
    category: finance
    port_map: "8084"
    author: Rotki
    developer: Rotki
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: rotki
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: rotki/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:55Z"
