name: zabbix
services:
    zabbix-agent:
        environment:
            ZBX_HOSTNAME: zabbix-agent
            ZBX_SERVER_HOST: zabbix-server
        hostname: zabbix-agent
        image: zabbix/zabbix-agent2:7.4.10-alpine@sha256:dc9a2ae2bebf401e8a5bac047e6b3f1f3b4566207101c9df6510be48b9fbda29
        init: true
        restart: on-failure
    zabbix-database:
        environment:
            POSTGRES_DB: zabbix
            POSTGRES_PASSWORD: zabbix
            POSTGRES_USER: zabbix
        hostname: zabbix-database
        image: postgres:13.18-alpine3.20@sha256:77815c1f18ae761b0e503503a494475a03149d7ce544934ccecdbafdb3956c94
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/zabbix/data/postgres:/var/lib/postgresql/data
    zabbix-frontend:
        depends_on:
            - zabbix-server
            - zabbix-database
        environment:
            DB_SERVER_HOST: zabbix-database
            PHP_TZ: UTC
            POSTGRES_PASSWORD: zabbix
            POSTGRES_USER: zabbix
            ZBX_SERVER_HOST: zabbix-server
        hostname: zabbix-frontend
        image: zabbix/zabbix-web-nginx-pgsql:7.4.10-alpine@sha256:b810d84400c4527473226f0ccdb7c29eee9397cabfaa220a8ed9135bd110e530
        ports:
            - 10052:8080
        restart: on-failure
    zabbix-server:
        depends_on:
            - zabbix-database
        environment:
            DB_SERVER_HOST: zabbix-database
            POSTGRES_PASSWORD: zabbix
            POSTGRES_USER: zabbix
        hostname: zabbix-server
        image: zabbix/zabbix-server-pgsql:7.4.10-alpine@sha256:944ac5ae2f58c643af43133a4c43e44fba856893e32ddcc73ee7ac1abab9c158
        init: true
        ports:
            - 10050:10050
        restart: on-failure
version: "3.7"

x-powerlab:
    store_app_id: zabbix
    title:
        en_us: Zabbix
    tagline:
        en_us: The all-in-one, open-source solution that lets you monitor anything
    icon: https://getumbrel.github.io/umbrel-apps-gallery/zabbix/icon.svg
    category: networking
    port_map: "10052"
    author: Zabbix LLC
    developer: Zabbix LLC
    main: zabbix-frontend
    source:
        catalog: umbrel-apps
        upstream_id: zabbix
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: zabbix/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:14:04Z"
