name: romm
services:
    db:
        environment:
            - MARIADB_ROOT_PASSWORD=umbrel
            - MARIADB_DATABASE=romm
            - MARIADB_USER=romm-user
            - MARIADB_PASSWORD=moneyprintergobrr
        healthcheck:
            interval: 10s
            retries: 5
            start_period: 30s
            test:
                - CMD
                - healthcheck.sh
                - --connect
                - --innodb_initialized
            timeout: 5s
        image: mariadb:11.4.5@sha256:5dfb3093333fa0ea53194ddef0a2bfa21d3b1e1353bd228b22610cd6fc0c04da
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/romm/data/db:/var/lib/mysql
    server:
        depends_on:
            db:
                condition: service_healthy
        environment:
            - DB_HOST=romm_db_1
            - DB_NAME=romm
            - DB_USER=romm-user
            - DB_PASSWD=moneyprintergobrr
            - ROMM_AUTH_SECRET_KEY=${APP_SEED}
        image: rommapp/romm:4.8.1@sha256:2b7a1714b287f69b081ad2a63bb8c2fa673666a17b2f21322b580b0cd51cb266
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/romm/data/resources:/romm/resources
            - /DATA/PowerLabAppData/romm/data/redis:/redis-data
            - /DATA/PowerLabAppData/romm/data/library:/romm/library
            - /DATA/PowerLabAppData/romm/data/assets:/romm/assets
            - /DATA/PowerLabAppData/romm/data/config:/romm/config
version: "3.7"

x-powerlab:
    store_app_id: romm
    title:
        en_us: RomM
    tagline:
        en_us: A beautiful, powerful, self-hosted rom manager
    icon: https://getumbrel.github.io/umbrel-apps-gallery/romm/icon.svg
    category: media
    port_map: "4002"
    author: rommapp
    developer: rommapp
    source:
        catalog: umbrel-apps
        upstream_id: romm
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: romm/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:43Z"
