name: solidtime
services:
    app:
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_DEBUG: "false"
            APP_ENV: production
            APP_FORCE_HTTPS: "false"
            APP_NAME: solidtime
            APP_URL: http://${DEVICE_DOMAIN_NAME}:8770
            AUTO_DB_MIGRATE: "true"
            CONTAINER_MODE: http
            DB_CONNECTION: pgsql
            DB_DATABASE: solidtime
            DB_HOST: db
            DB_PASSWORD: solidtime
            DB_PORT: "5432"
            DB_SSLMODE: require
            DB_USERNAME: solidtime
            FILESYSTEM_DISK: local
            GOTENBERG_URL: http://gotenberg:3000
            LOG_CHANNEL: stderr_daily
            LOG_LEVEL: debug
            MAIL_ENCRYPTION: tls
            MAIL_FROM_ADDRESS: no-reply@your-domain.com
            MAIL_FROM_NAME: solidtime
            MAIL_HOST: ""
            MAIL_MAILER: smtp
            MAIL_PASSWORD: ""
            MAIL_PORT: ""
            MAIL_USERNAME: ""
            PUBLIC_FILESYSTEM_DISK: public
            QUEUE_CONNECTION: database
            SUPER_ADMINS: umbrel@umbrel.local
            TRUSTED_PROXIES: 0.0.0.0/0,2000:0:0:0:0:0:0:0/3
            VITE_APP_NAME: solidtime
        healthcheck:
            test:
                - CMD-SHELL
                - curl --fail http://localhost:8000/health-check/up || exit 1
        image: solidtime/solidtime:0.12.1@sha256:e6c67c722b7237193b77eba7d9808f2b6bc65bcb232caaa6ecd1306a2daecfd3
        ports:
            - 8770:8000
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/solidtime/data/app:/var/www/html/storage
    db:
        environment:
            PGPASSWORD: soldtime
            POSTGRES_DB: solidtime
            POSTGRES_PASSWORD: solidtime
            POSTGRES_USER: solidtime
        healthcheck:
            retries: 3
            test:
                - CMD
                - pg_isready
                - -q
                - -d
                - solidtime
                - -U
                - solidtime
            timeout: 5s
        image: postgres:17.3@sha256:0321e2252ebfeecb8bc1a899755084d29bce872953e1a5a3e25ec0860b739098
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/solidtime/data/db:/var/lib/postgresql/data
    gotenberg:
        healthcheck:
            test:
                - CMD
                - curl
                - --silent
                - --fail
                - http://localhost:3000/health
        image: gotenberg/gotenberg:8.17.1@sha256:46e7b68adeadda1794a9ab194f1e2939f5b09ff21aadef6000e84102c9af6dd5
        restart: on-failure
        user: 1000:1000
    queue:
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_DEBUG: "false"
            APP_ENV: production
            APP_FORCE_HTTPS: "false"
            APP_NAME: solidtime
            APP_URL: http://${DEVICE_DOMAIN_NAME}:8770
            CONTAINER_MODE: worker
            DB_CONNECTION: pgsql
            DB_DATABASE: solidtime
            DB_HOST: db
            DB_PASSWORD: solidtime
            DB_PORT: "5432"
            DB_SSLMODE: require
            DB_USERNAME: solidtime
            FILESYSTEM_DISK: local
            GOTENBERG_URL: http://gotenberg:3000
            LOG_CHANNEL: stderr_daily
            LOG_LEVEL: debug
            MAIL_ENCRYPTION: tls
            MAIL_FROM_ADDRESS: no-reply@your-domain.com
            MAIL_FROM_NAME: solidtime
            MAIL_HOST: ""
            MAIL_MAILER: smtp
            MAIL_PASSWORD: ""
            MAIL_PORT: ""
            MAIL_USERNAME: ""
            PUBLIC_FILESYSTEM_DISK: public
            QUEUE_CONNECTION: database
            SUPER_ADMINS: umbrel@umbrel.local
            TRUSTED_PROXIES: 0.0.0.0/0,2000:0:0:0:0:0:0:0/3
            VITE_APP_NAME: solidtime
            WORKER_COMMAND: php /var/www/html/artisan queue:work
        healthcheck:
            test:
                - CMD
                - healthcheck
        image: solidtime/solidtime:0.12.1@sha256:e6c67c722b7237193b77eba7d9808f2b6bc65bcb232caaa6ecd1306a2daecfd3
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/solidtime/data/app:/var/www/html/storage
    scheduler:
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_DEBUG: "false"
            APP_ENV: production
            APP_FORCE_HTTPS: "false"
            APP_NAME: solidtime
            APP_URL: http://${DEVICE_DOMAIN_NAME}:8770
            CONTAINER_MODE: scheduler
            DB_CONNECTION: pgsql
            DB_DATABASE: solidtime
            DB_HOST: db
            DB_PASSWORD: solidtime
            DB_PORT: "5432"
            DB_SSLMODE: require
            DB_USERNAME: solidtime
            FILESYSTEM_DISK: local
            GOTENBERG_URL: http://gotenberg:3000
            LOG_CHANNEL: stderr_daily
            LOG_LEVEL: debug
            MAIL_ENCRYPTION: tls
            MAIL_FROM_ADDRESS: no-reply@your-domain.com
            MAIL_FROM_NAME: solidtime
            MAIL_HOST: ""
            MAIL_MAILER: smtp
            MAIL_PASSWORD: ""
            MAIL_PORT: ""
            MAIL_USERNAME: ""
            PUBLIC_FILESYSTEM_DISK: public
            QUEUE_CONNECTION: database
            SUPER_ADMINS: umbrel@umbrel.local
            TRUSTED_PROXIES: 0.0.0.0/0,2000:0:0:0:0:0:0:0/3
            VITE_APP_NAME: solidtime
        healthcheck:
            test:
                - CMD
                - healthcheck
        image: solidtime/solidtime:0.12.1@sha256:e6c67c722b7237193b77eba7d9808f2b6bc65bcb232caaa6ecd1306a2daecfd3
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/solidtime/data/app:/var/www/html/storage

x-powerlab:
    store_app_id: solidtime
    title:
        en_us: Solidtime
    tagline:
        en_us: A simple, secure, and private time tracking app
    description:
        en_us: 'solidtime - The modern Open-Source TimeTracker [](https://github.com/solidtime-io/solidtime/blob/main/LICENSE.md) [](https://codecov.io/gh/solidtime-io/solidtime) solidtime is a modern open-source time tracking application for Freelancers and Agencies. Features - Time tracking: Track your time with a modern and easy-to-use interface - Projects: Create and manage projects and assign project members - Tasks: Create and manage tasks and assign tasks to projects - Clients: Create and manage clients and assign clients to projects - Billable rates: Set billable rates for projects, project members, organization members and organizations - Multiple organizations: Create and manage multiple organizations with one account - Roles and permissions: Create and manage organizations - Import: Import your time tracking data from other time tracking applications (Supported: Toggl, Clockify, Timeentry CSV) Self Hosting If you are looking into self-hosting solidtime, you can find the guides here We also have an examples repository here If you do not want to self-host solidtime or try it out you can sign up for solidtime cloud Issues & Feature Requests If you find any **bugs in solidtime**, please feel free to **open an issue** in this repository, with instructions on how to reproduce the bug. If you have a **feature request**, please **create a discussion** in this repository. Contributing Please…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/solidtime/icon.svg
    category: files
    port_map: "8770"
    author: Solidtime
    developer: Solidtime
    main: app
    source:
        catalog: umbrel-apps
        upstream_id: solidtime
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: solidtime/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:57Z"
