name: adguard-home
services:
    server:
        cap_add:
            - NET_ADMIN
        command:
            - --no-check-update
            - -c
            - /opt/adguardhome/conf/AdGuardHome.yaml
            - -w
            - /opt/adguardhome/work
            - --web-addr
            - 0.0.0.0:8095
        image: adguard/adguardhome:v0.107.74@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
        network_mode: host
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/adguard-home/data/work:/opt/adguardhome/work
            - /DATA/PowerLabAppData/adguard-home/data/conf:/opt/adguardhome/conf
version: "3.7"

x-powerlab:
    store_app_id: adguard-home
    title:
        en_us: AdGuard Home
    tagline:
        en_us: Network-wide software for blocking ads and tracking
    icon: https://getumbrel.github.io/umbrel-apps-gallery/adguard-home/icon.svg
    category: networking
    port_map: "8095"
    author: Adguard
    developer: Adguard
    source:
        catalog: umbrel-apps
        upstream_id: adguard-home
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: adguard-home/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:26Z"
