name: frigate
services:
    web:
        environment:
            FRIGATE_RTSP_PASSWORD: ${APP_PASSWORD}
        image: ghcr.io/blakeblackshear/frigate:0.17.1@sha256:1724960349dad0bd2ae8ec884171a6fd5755a4dc242a0e66cadbda9c0e85c99b
        ports:
            - 8554:8554
            - 8555:8555/tcp
            - 8555:8555/udp
        privileged: true
        restart: on-failure
        shm_size: 128mb
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /DATA/PowerLabAppData/frigate/data/config:/config
            - /DATA/PowerLabAppData/frigate/data/storage:/media/frigate
version: "3.7"

x-powerlab:
    store_app_id: frigate
    title:
        en_us: Frigate
    tagline:
        en_us: A complete and local NVR
    icon: https://getumbrel.github.io/umbrel-apps-gallery/frigate/icon.svg
    category: automation
    port_map: "5004"
    author: Blake Blackshear
    developer: Blake Blackshear
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: frigate
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: frigate/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:35Z"
