name: chromium
services:
    chromium:
        environment:
            - PUID=1000
            - PGID=1000
        image: ghcr.io/linuxserver/chromium:version-8d3cb5f1@sha256:d7c5f7faf5fe524117fd73c4d446e1bf81bccd0d64d073a30b8c9819fdf105d6
        ports:
            - 30099:3000
        restart: on-failure
        shm_size: 1gb
        volumes:
            - /DATA/PowerLabAppData/chromium/data:/config
version: "3.7"

x-powerlab:
    store_app_id: chromium
    title:
        en_us: Chromium
    tagline:
        en_us: The open-source browser project
    icon: https://getumbrel.github.io/umbrel-apps-gallery/chromium/icon.svg
    category: networking
    port_map: "30099"
    author: The Chromium Project
    developer: The Chromium Project
    main: chromium
    source:
        catalog: umbrel-apps
        upstream_id: chromium
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: chromium/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:30Z"
