name: threema
services:
    web:
        image: dennysubke/threema-web:v2.6.3@sha256:8c65ceb537a7a85bb98ef38263860dc6bede8faef620143ec01a584dec26878d
        restart: on-failure
version: "3.7"

x-powerlab:
    store_app_id: threema
    title:
        en_us: Threema Web
    tagline:
        en_us: An intuitive and secure web client for Threema users
    icon: https://getumbrel.github.io/umbrel-apps-gallery/threema/icon.svg
    category: files
    port_map: "8855"
    author: Threema GmbH
    developer: Threema GmbH
    source:
        catalog: umbrel-apps
        upstream_id: threema
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: threema/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:53Z"
