name: threema
services:
    web:
        image: dennysubke/threema-web:v2.6.3@sha256:8c65ceb537a7a85bb98ef38263860dc6bede8faef620143ec01a584dec26878d
        ports:
            - 8855:80
        restart: on-failure
version: "3.7"

x-powerlab:
    store_app_id: threema
    title:
        en_us: Threema Web
    tagline:
        en_us: An intuitive and secure web client for Threema users
    icon: https://getumbrel.github.io/umbrel-apps-gallery/threema/icon.svg
    category: files
    port_map: "8855"
    author: Threema GmbH
    developer: Threema GmbH
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: threema
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: threema/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:27:03Z"
