name: jellyfin
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        hostname: ${DEVICE_HOSTNAME}
        image: linuxserver/jellyfin:10.11.8@sha256:e93bc100c6da07bd058678e4b634e4e71031fe840227e2ed03a1104f032bebe8
        ports:
            - 7359:7359/udp
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/jellyfin/data/config:/config
            - /DATA/data/storage/downloads:/downloads
version: "3.7"

x-powerlab:
    store_app_id: jellyfin
    title:
        en_us: Jellyfin
    tagline:
        en_us: The Free Software Media System
    icon: https://getumbrel.github.io/umbrel-apps-gallery/jellyfin/icon.svg
    category: media
    port_map: "8096"
    author: Jellyfin
    developer: Jellyfin
    source:
        catalog: umbrel-apps
        upstream_id: jellyfin
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: jellyfin/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:43:07Z"
