name: jackett
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        image: linuxserver/jackett:0.24.1870@sha256:1b1662447fd233b86c34ba1e7cdfccbab0a1f073fbacc20bf0f63e5a7138ac6e
        ports:
            - 9117:9117
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/jackett/data:/config
            - /DATA/data/storage/downloads:/downloads
version: "3.7"

x-powerlab:
    store_app_id: jackett
    title:
        en_us: Jackett
    tagline:
        en_us: API support for your favorite torrent trackers
    icon: https://getumbrel.github.io/umbrel-apps-gallery/jackett/icon.svg
    category: media
    port_map: "9117"
    author: Jackett
    developer: Jackett
    main: server
    source:
        catalog: umbrel-apps
        upstream_id: jackett
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: jackett/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:39Z"
