name: jackett
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        image: linuxserver/jackett:0.24.1846@sha256:9e8c40423e92d1f4dfaa6d0b63f9b44953a788f60a18fed7756d5a837f9ce966
        ports:
            - 9117:9117
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/jackett/data:/config
            - /DATA/data/storage/downloads:/downloads
version: "3.7"

x-powerlab:
    store_app_id: jackett
    title:
        en_us: Jackett
    tagline:
        en_us: API support for your favorite torrent trackers
    icon: https://getumbrel.github.io/umbrel-apps-gallery/jackett/icon.svg
    category: media
    port_map: "9117"
    author: Jackett
    developer: Jackett
    source:
        catalog: umbrel-apps
        upstream_id: jackett
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: jackett/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:43:07Z"
