name: ittools
services:
    app:
        cpu_shares: 768
        image: corentinth/it-tools:2024.10.22-7ca5933@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
        mem_limit: 2g
        ports:
            - 8786:80
        restart: on-failure
        security_opt:
            - no-new-privileges:true
version: "3.7"

x-powerlab:
    store_app_id: ittools
    title:
        en_us: IT-Tools
    tagline:
        en_us: An array of handy online tools for developers
    description:
        en_us: '<picture> <source srcset="./.github/logo-dark.png" media="(prefers-color-scheme: light)"> <source srcset="./.github/logo-white.png" media="(prefers-color-scheme: dark)"> <img src="./.github/logo-dark.png" alt="logo"> </picture> <p align="center"> Useful tools for developer and people working in IT. <a href="https://it-tools.tech">Try it!</a> </p> Functionalities and roadmap Please check the issues to see if some feature listed to be implemented. You have an idea of a tool? Submit a feature request! Self host Self host solutions for your homelab **From docker hub:** **From github packages:** **Other solutions:** - Cloudron - Tipi - Unraid Contribute Recommended IDE Setup VSCode with the following extensions: - Volar (and disable Vetur) - TypeScript Vue Plugin (Volar). - ESLint - i18n Ally with the following settings: Type Support for Imports in TS TypeScript cannot handle type information for imports by default, so we replace the CLI with for type checking. In editors, we need TypeScript Vue Plugin (Volar) to make the TypeScript language service aware of types. If the standalone TypeScript plugin doesn''t feel fast enough to you, Volar has also implemented a Take Over Mode that is more performant. You can enable it by the following steps: 1. Disable the built-in TypeScript Extension 1. Run from VSCode''s command palette 2. Find , right click and select 2. Reload the VSCode…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/ittools/icon.svg
    category: developer
    port_map: "8786"
    author: Corentin Thomasset
    developer: Corentin Thomasset
    main: app
    source:
        catalog: umbrel-apps
        upstream_id: ittools
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: ittools/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:39Z"
