name: synapse
services:
    server:
        command: |-
            -c './start.py generate && ./start.py migrate_config && echo -e "
            enable_registration_without_verification: true" >> /data/homeserver.yaml && exec ./start.py'
        entrypoint: bash
        environment:
            GID: "1000"
            SYNAPSE_ENABLE_REGISTRATION: "yes"
            SYNAPSE_HTTP_PORT: ${APP_SYNAPSE_PORT}
            SYNAPSE_NO_TLS: "yes"
            SYNAPSE_REPORT_STATS: "yes"
            SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
            UID: "1000"
        image: matrixdotorg/synapse:v1.152.1@sha256:ea13612748d2c3cd7d37314e4d2bb3833831e7fe9c1cc2ba2a05a0e51ab78297
        ports:
            - 8008:8008
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/synapse/data/synapse:/data
version: "3.7"

x-powerlab:
    store_app_id: synapse
    title:
        en_us: Synapse
    tagline:
        en_us: Matrix homeserver
    icon: https://getumbrel.github.io/umbrel-apps-gallery/synapse/icon.svg
    category: social
    port_map: "8008"
    author: Element
    developer: Element
    main: server
    source:
        catalog: umbrel-apps
        upstream_id: synapse
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: synapse/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:58Z"
