name: remmina
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        image: linuxserver/remmina:1.4.35@sha256:ca2b6788bad28d864086649fc276ce696cac9cdf69e6976b85497b341ed07d8d
        ports:
            - 8764:3000
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/remmina/data/config:/config
version: "3.7"

x-powerlab:
    store_app_id: remmina
    title:
        en_us: Remmina
    tagline:
        en_us: Remote access screen and file sharing
    icon: https://getumbrel.github.io/umbrel-apps-gallery/remmina/icon.svg
    category: networking
    port_map: "8764"
    author: Remmina
    developer: Remmina
    main: server
    source:
        catalog: umbrel-apps
        upstream_id: remmina
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: remmina/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:26:56Z"
