name: forgejo
services:
    db:
        environment:
            POSTGRES_DB: forgejo
            POSTGRES_PASSWORD: forgejo
            POSTGRES_USER: forgejo
        healthcheck:
            interval: 5s
            retries: 5
            test:
                - CMD-SHELL
                - pg_isready -U forgejo
            timeout: 5s
        image: postgres:17.3@sha256:0321e2252ebfeecb8bc1a899755084d29bce872953e1a5a3e25ec0860b739098
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/forgejo/data/db:/var/lib/postgresql/data
    server:
        depends_on:
            db:
                condition: service_healthy
        environment:
            FORGEJO__database__DB_TYPE: postgres
            FORGEJO__database__HOST: forgejo_db_1:5432
            FORGEJO__database__NAME: forgejo
            FORGEJO__database__PASSWD: forgejo
            FORGEJO__database__USER: forgejo
            FORGEJO__security__INSTALL_LOCK: "true"
            FORGEJO__server__DOMAIN: ${APP_DOMAIN}
            FORGEJO__server__HTTP_PORT: 8101
            FORGEJO__server__SSH_DOMAIN: ${APP_DOMAIN}
            FORGEJO__server__SSH_LISTEN_PORT: ${APP_FORGEJO_SSH_PORT}
            FORGEJO__server__SSH_PORT: ${APP_FORGEJO_SSH_PORT}
            FORGEJO__server__START_SSH_SERVER: "true"
        image: codeberg.org/forgejo/forgejo:15.0.2-rootless@sha256:cc2d74fb4c30385a8ee34de8c8f83344f7316cec70bd2cc7eb82b2802fa28e0b
        ports:
            - 18000:18001
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/forgejo/data/forgejo/data:/var/lib/gitea
            - /DATA/PowerLabAppData/forgejo/data/forgejo/config:/etc/gitea
version: "3.7"

x-powerlab:
    store_app_id: forgejo
    title:
        en_us: Forgejo
    tagline:
        en_us: A self-hosted lightweight software forge
    icon: https://getumbrel.github.io/umbrel-apps-gallery/forgejo/icon.svg
    category: developer
    port_map: "8101"
    author: Forgejo Community
    developer: Forgejo Community
    source:
        catalog: umbrel-apps
        upstream_id: forgejo
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: forgejo/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:11Z"
