name: picsur
services:
    db:
        cpu_shares: 1024
        environment:
            POSTGRES_DB: picsur
            POSTGRES_PASSWORD: picsurpass
            POSTGRES_USER: picsuruser
        healthcheck:
            interval: 10s
            retries: 10
            test:
                - CMD
                - pg_isready
                - -q
                - -d
                - picsur
                - -U
                - picsuruser
            timeout: 45s
        image: postgres:17.4@sha256:fe3f571d128e8efadcd8b2fde0e2b73ebab6dbec33f6bfe69d98c682c7d8f7bd
        mem_limit: 1g
        restart: on-failure
        security_opt:
            - no-new-privileges:true
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/picsur/data/db:/var/lib/postgresql/data:rw
    web:
        depends_on:
            db:
                condition: service_healthy
        environment:
            PICSUR_ADMIN_PASSWORD: ${APP_PASSWORD}
            PICSUR_DB_DATABASE: picsur
            PICSUR_DB_HOST: db
            PICSUR_DB_PASSWORD: picsurpass
            PICSUR_DB_PORT: 5432
            PICSUR_DB_USERNAME: picsuruser
            PICSUR_MAX_FILE_SIZE: 128000000000
            PICSUR_PORT: 8286
        image: ghcr.io/caramelfur/picsur:0.5.6@sha256:209ce21d338cd7d9a1adc838a67695e903149359bf192359819607df1b3c4417
        ports:
            - 8286:8286
        restart: on-failure
        user: 1000:1000
version: "3.7"

x-powerlab:
    store_app_id: picsur
    title:
        en_us: Picsur
    tagline:
        en_us: An easy to use image sharing service
    icon: https://getumbrel.github.io/umbrel-apps-gallery/picsur/icon.svg
    category: files
    port_map: "8286"
    author: CaramelFur
    developer: CaramelFur
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: picsur
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: picsur/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:52Z"
