name: affine
services:
    db:
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: affine
            POSTGRES_PASSWORD: affine
            POSTGRES_USER: affine
        healthcheck:
            interval: 10s
            retries: 5
            test:
                - CMD-SHELL
                - pg_isready -U affine
            timeout: 5s
        image: postgres:16.2@sha256:f58300ac8d393b2e3b09d36ea12d7d24ee9440440e421472a300e929ddb63460
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/affine/data/storage/postgres:/var/lib/postgresql/data
    migration:
        command:
            - sh
            - -c
            - node ./scripts/self-host-predeploy
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            - AFFINE_CONFIG_PATH=/root/.affine/config
            - REDIS_SERVER_HOST=affine_redis_1
            - DATABASE_URL=postgres://affine:affine@affine_db_1:5432/affine
            - NODE_ENV=production
        image: ghcr.io/toeverything/affine:0.26.3@sha256:725aaceb0ed94d4b832ae6ef9414503291c9b2b4f60bd6f3c7eef571b6149add
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/affine/data/config:/root/.affine/config
            - /DATA/PowerLabAppData/affine/data/storage/blob:/root/.affine/storage
    redis:
        healthcheck:
            interval: 10s
            retries: 5
            test:
                - CMD
                - redis-cli
                - --raw
                - incr
                - ping
            timeout: 5s
        image: redis:7.2.4@sha256:e647cfe134bf5e8e74e620f66346f93418acfc240b71dd85640325cb7cd01402
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/affine/data/storage/redis:/data
    web:
        depends_on:
            db:
                condition: service_healthy
            migration:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
        environment:
            - AFFINE_CONFIG_PATH=/root/.affine/config
            - REDIS_SERVER_HOST=affine_redis_1
            - DATABASE_URL=postgres://affine:affine@affine_db_1:5432/affine
            - NODE_ENV=production
        image: ghcr.io/toeverything/affine:0.26.3@sha256:725aaceb0ed94d4b832ae6ef9414503291c9b2b4f60bd6f3c7eef571b6149add
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/affine/data/config:/root/.affine/config
            - /DATA/PowerLabAppData/affine/data/storage/blob:/root/.affine/storage

x-powerlab:
    store_app_id: affine
    title:
        en_us: Affine
    tagline:
        en_us: Open source alternative to Notion, Miro, and Airtable
    icon: https://getumbrel.github.io/umbrel-apps-gallery/affine/icon.svg
    category: files
    port_map: "3013"
    author: toeverything
    developer: toeverything
    source:
        catalog: umbrel-apps
        upstream_id: affine
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: affine/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:06Z"
