version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wizarr_app_1
      APP_PORT: 5690
      
  app:
    image: ghcr.io/wizarrrr/wizarr:v2026.4.0@sha256:19da537e01b5470cb34b083b5ac64cb534dd27084d9d66bc634e96c1f3976884
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_BUILTIN_AUTH=false
      - TZ=UTC

x-powerlab:
    store_app_id: wizarr
    title:
        en_us: Wizarr
    tagline:
        en_us: An advanced invitation and management system for media servers
    description:
        en_us: "Wizarr > \U0001F680 **Development Relaunched:** We're excited to announce that **Wizarr is back in active development**! <br></br> <p align=\"center\"> <img src=\"./app/static/wizarr-logo.png\" height=\"200\"> <p></p> </p> <br></br> [](https://github.com/wizarrrr/wizarr) [](https://github.com/wizarrrr/wizarr) [](https://github.com/wizarrrr/wizarr) [](https://discord.gg/NYxwcjCK9x) Wizarr is an automatic user invitation and management system for Plex, Jellyfin, Emby, Audiobookshelf, Romm, Komga and Kavita. Create a unique invite link and share it with users — they’ll be automatically added to your media server and guided through downloading apps, accessing request systems, and more! **The problem**: Inviting your Friends/Family to your Plex server Is complicated and tedious. It's also a hard concept for them to get their head around. **The solution**: Wizarr makes it easy to invite users to your server by simply sending them a link, and guides them through the process of getting set up. ✨ Major Features - Automatic invitations for Plex, Jellyfin, Emby, AudiobookShelf, Komga, Kavita and Romm - Secure, user-friendly invitation process - Plug-and-play SSO support* - Multi-tiered invitation access - Time-limited membership options - Pre-invite and post-invite wizard steps - Setup guide for media apps (like Plex) - Request system integration (Overseerr, Ombi, etc.) - Discord invite support - Fully customisable with your own HTML snippets \U0001F680 Getting Started Check out our…"
    icon: https://getumbrel.github.io/umbrel-apps-gallery/wizarr/icon.svg
    category: media
    port_map: "5690"
    author: Wizarr
    developer: Wizarr
    source:
        catalog: umbrel-apps
        upstream_id: wizarr
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 0299c400450d07fee62d3dcb0e6c24b00f359b51
        upstream_path: wizarr/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T03:53:19Z"
