name: wordpress
services:
    app:
        depends_on:
            - db
        environment:
            - WORDPRESS_DB_HOST=wordpress_db_1
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_DB_USER=umbrel
            - WORDPRESS_DB_PASSWORD=umbrelwordpress
        image: wordpress:6.9.4@sha256:ee74dc0ebbe7ec43b7f473c0fb4f1dfb6b211d7785f0a95bcdfa10e628c2e67f
        ports:
            - 8567:80
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/wordpress/data/wordpress:/var/www/html
    db:
        environment:
            - MYSQL_ROOT_PASSWORD=umbrelwordpressroot
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=umbrel
            - MYSQL_PASSWORD=umbrelwordpress
        image: mariadb:11.5.2@sha256:2d50fe0f77dac919396091e527e5e148a9de690e58f32875f113bef6506a17f5
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/wordpress/data/db:/var/lib/mysql
version: "3.7"

x-powerlab:
    store_app_id: wordpress
    title:
        en_us: WordPress
    tagline:
        en_us: The open source publishing platform of choice for millions of websites worldwide
    icon: https://getumbrel.github.io/umbrel-apps-gallery/wordpress/icon.svg
    category: social
    port_map: "8567"
    author: WordPress
    developer: WordPress
    source:
        catalog: umbrel-apps
        upstream_id: wordpress
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: wordpress/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:43:52Z"
