name: just-download
services:
    web:
        environment:
            CONFIG: '{"indexers": [], "transmission": {"host": "transmission_server_1", "port": 9091}}'
            CONFIG_LOCATION: /config/config.json
            LOCK_TRANSMISSION_CONFIG: 1
        image: codeberg.org/highghlow/just-download:v1.0.9@sha256:96d8ed20104418ca41ccc8fc7001889f827bc60235b71b8e9aa19d1f5a6e4db7
        ports:
            - 3684:5000
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/just-download/data/config:/config
version: "3.7"

x-powerlab:
    store_app_id: just-download
    title:
        en_us: Just. Download.
    tagline:
        en_us: Download torrents. Just. Download.
    icon: https://getumbrel.github.io/umbrel-apps-gallery/just-download/icon.svg
    category: media
    port_map: "3684"
    author: highghlow
    developer: highghlow
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: just-download
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: just-download/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:40Z"
