name: lunalytics
services:
    web:
        healthcheck:
            interval: 10s
            retries: 3
            start_period: 90s
            test:
                - CMD-SHELL
                - nc -z 127.0.0.1 2308 || exit 1
            timeout: 5s
        image: ksjaay/lunalytics:0.10.23@sha256:b1e44f9e647e3e240400eafc914facafbfad2cc87d6c4f02d823226dd9731511
        ports:
            - 8183:2308
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/lunalytics/data/lunalytics_data:/app/data:rw
            - /DATA/PowerLabAppData/lunalytics/data/logs:/app/logs:rw
version: "3.7"

x-powerlab:
    store_app_id: lunalytics
    title:
        en_us: Lunalytics
    tagline:
        en_us: A monitoring tool for teams
    description:
        en_us: "<div align=\"center\"> <img src=\"https://raw.githubusercontent.com/KSJaay/Lunalytics/main/public/LogoWithName.png\" width=\"300px\" alt=\"Lunalytics logo\" /> </div> <h2 align=\"center\">Open source monitoring tool built with Node.js & React</h2> <div align=\"center\"> <a href=\"https://lunalytics.xyz\">Documentation</a> · <a href=\"https://demo.lunalytics.xyz\">Try live demo</a> · <a href=\"https://roadmap.lunalytics.xyz\">Roadmap</a> · <a href=\"https://discord.gg/HkpDnUdf4u\">Discord</a> </div> \U0001F4D4 Features - Easy to self-host - Monitor uptime for: - HTTP(s) - TCP - PING - JSON Query - PUSH - Docker Containers - Support for multiple users - Fully customisable status/dashboard pages - Incident management - Advance role based access control - Clean and easy to use UX/UI - Customizable user profiles/themes/colors - Single sign on support (SSO) - Custom (Authentik, Authelia, Keycloak, etc...) - Discord - Google - GitHub - Slack - Twitch - Support for notifications - Apprise - Discord - Email (SMTP) - Home Assistant - Pushover - Slack - Telegram - Webhook - More to come... \U0001F680 Getting Started > [!CAUTION] > > This project is under active development and still in beta, things may randomly break. But I'll do my best to fix them as soon as possible. Docker Docker Compose Requirements Make sure you have the following applications installed before starting: - Nodejs (v22.14.0 or higher) - Npm or Yarn - Git Clone application Setup application Lunalytics…"
    icon: https://getumbrel.github.io/umbrel-apps-gallery/lunalytics/icon.svg
    category: networking
    port_map: "8183"
    author: KSJaay
    developer: KSJaay
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: lunalytics
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: lunalytics/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:43Z"
