name: tautulli
services:
    web:
        environment:
            - PUID=1000
            - PGID=1000
        image: linuxserver/tautulli:2.17.1@sha256:7077fd6654547c225ca5a740c4c954379129589f875c84cbe138641d4dd8a9d9
        ports:
            - 8212:8181
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/tautulli/data/config:/config
version: "3.7"

x-powerlab:
    store_app_id: tautulli
    title:
        en_us: tautulli
    tagline:
        en_us: Monitor your Plex Media Server
    icon: https://getumbrel.github.io/umbrel-apps-gallery/tautulli/icon.svg
    category: media
    port_map: "8212"
    author: Tautulli
    developer: Tautulli
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: tautulli
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: tautulli/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:27:02Z"
