name: sqlitebrowser
services:
    app:
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/CET
        image: linuxserver/sqlitebrowser:3.13.1@sha256:1b1e81f0af222af3353a4c8d3c4737264a1816a43e4410819430335fa099b1da
        ports:
            - 8887:3000
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/sqlitebrowser/data/config:/config

x-powerlab:
    store_app_id: sqlitebrowser
    title:
        en_us: SQLite Browser
    tagline:
        en_us: A database browser for SQLite
    icon: https://getumbrel.github.io/umbrel-apps-gallery/sqlitebrowser/icon.svg
    category: developer
    port_map: "8887"
    author: SQLiteBrowser
    developer: SQLiteBrowser
    main: app
    source:
        catalog: umbrel-apps
        upstream_id: sqlitebrowser
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: sqlitebrowser/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:27:01Z"
