name: open-webui
services:
    web:
        environment:
            OLLAMA_BASE_URL: $APP_OLLAMA_URL
        image: ghcr.io/open-webui/open-webui:v0.9.5@sha256:e045bde3b004cc7f8c319412345eb56c87ea6ac57031534a31ca37ad5424beb3
        ports:
            - 2876:8080
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/open-webui/data/open-webui:/app/backend/data
version: "3.7"

x-powerlab:
    store_app_id: open-webui
    title:
        en_us: Open WebUI
    tagline:
        en_us: Chat with Ollama models like DeepSeek-R1 and LLama, or use an OpenAI API key
    description:
        en_us: "Open WebUI \U0001F44B [](https://discord.gg/5rJgQTnV4s) [](https://github.com/sponsors/tjbck) **Open WebUI is an extensible, feature-rich, and user-friendly self-hosted AI platform designed to operate entirely offline.** It supports various LLM runners like **Ollama** and **OpenAI-compatible APIs**, with **built-in inference engine** for RAG, making it a **powerful AI deployment solution**. Passionate about open-source AI? Join our team → > [!TIP] > **Looking for an Enterprise Plan?** – **Speak with Our Sales Team Today!** > > Get **enhanced capabilities**, including **custom theming and branding**, **Service Level Agreement (SLA) support**, **Long-Term Support (LTS) versions**, and **more!** For more information, be sure to check out our Open WebUI Documentation. Key Features of Open WebUI ⭐ - \U0001F680 **Effortless Setup**: Install seamlessly using Docker or Kubernetes (kubectl, kustomize or helm) for a hassle-free experience with support for both and tagged images. - \U0001F91D **Ollama/OpenAI API Integration**: Effortlessly integrate OpenAI-compatible APIs for versatile conversations alongside Ollama models. Customize the OpenAI API URL to link with **LMStudio, GroqCloud, Mistral, OpenRouter, and more**. - \U0001F6E1️ **Granular Permissions and User Groups**: By allowing administrators to create detailed user roles and permissions, we ensure a secure user environment. This granularity not only enhances security but also allows for customized user experiences, fostering a sense of…"
    icon: https://getumbrel.github.io/umbrel-apps-gallery/open-webui/icon.svg
    category: ai
    port_map: "2876"
    author: Open WebUI
    developer: Open WebUI
    source:
        catalog: umbrel-apps
        upstream_id: open-webui
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: open-webui/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:43:30Z"
