name: rusty-kaspad
services:
    frontend:
        depends_on:
            - kaspad
        image: elldee/kaspa-frontend:v0.4.1@sha256:a77573dfbc706b632ba24b9087685dc0b44d588c60b5399e2c2df2a19bd38a93
        ports:
            - 4321:4321
        restart: on-failure
        stop_grace_period: 1m
    kaspad:
        image: kaspanet/rusty-kaspad:v1.1.0@sha256:150ffa0c0dcc6497951f9199d1ba3e48c7d91ef958846b28c9fb5045459a2dca
        ports:
            - 16110:16110
            - 16111:16111
            - 17110:17110
            - 18110:18110
        restart: on-failure
        stop_grace_period: 3m
        volumes:
            - /DATA/PowerLabAppData/rusty-kaspad/data/app:/app/data
version: "3.7"

x-powerlab:
    store_app_id: rusty-kaspad
    title:
        en_us: Rusty Kaspad
    tagline:
        en_us: A Rust implementation of a Kaspa full node
    icon: https://getumbrel.github.io/umbrel-apps-gallery/rusty-kaspad/icon.svg
    category: crypto
    port_map: "4321"
    author: Kaspa Community
    developer: Kaspa Community
    main: frontend
    source:
        catalog: umbrel-apps
        upstream_id: rusty-kaspad
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: rusty-kaspad/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:55Z"
