name: code-server
services:
    server:
        environment:
            PASSWORD: $APP_PASSWORD
        image: codercom/code-server:4.118.0@sha256:4aff9947c113487113201da811564fade1af5f23038b4d683998d024eebbac92
        ports:
            - 8091:8080
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/code-server/data:/home/coder
version: "3.7"

x-powerlab:
    store_app_id: code-server
    title:
        en_us: code-server
    tagline:
        en_us: Run VS Code on your Umbrel
    icon: https://getumbrel.github.io/umbrel-apps-gallery/code-server/icon.svg
    category: developer
    port_map: "8091"
    author: Coder
    developer: Coder
    main: server
    source:
        catalog: umbrel-apps
        upstream_id: code-server
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: code-server/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:30Z"
