name: thelounge
services:
    web:
        image: ghcr.io/thelounge/thelounge:v4.4.3@sha256:c0565787e0c44951df4ea77840519a41cfe6a4ec040bf1bda928a91866cc3e5e
        ports:
            - 9003:9000
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/thelounge/data:/var/opt/thelounge
version: "3.7"

x-powerlab:
    store_app_id: thelounge
    title:
        en_us: The Lounge
    tagline:
        en_us: Modern web IRC client designed for self-hosting
    icon: https://getumbrel.github.io/umbrel-apps-gallery/thelounge/icon.svg
    category: social
    port_map: "9003"
    author: The Lounge Team
    developer: The Lounge Team
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: thelounge
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: thelounge/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:59Z"
