name: firefox
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        image: linuxserver/firefox:139.0.4@sha256:01c090309f63bc619a1df80bf14fdc87cb6fd922d956da48a968a60ab5a0df6d
        restart: on-failure
        shm_size: 1gb
        volumes:
            - /DATA/PowerLabAppData/firefox/data/config:/config
version: "3.7"

x-powerlab:
    store_app_id: firefox
    title:
        en_us: Firefox
    tagline:
        en_us: Firefox is a free and open-source web browser
    icon: https://getumbrel.github.io/umbrel-apps-gallery/firefox/icon.svg
    category: networking
    port_map: "3434"
    author: Mozilla Foundation
    developer: Mozilla Foundation
    source:
        catalog: umbrel-apps
        upstream_id: firefox
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: firefox/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:11Z"
