name: etherpad
services:
    app:
        depends_on:
            - postgres
        environment:
            ADMIN_PASSWORD: ${APP_PASSWORD}
            ALLOW_UNKNOWN_FILE_ENDS: "true"
            CI: "true"
            DB_CHARSET: utf8mb4
            DB_HOST: etherpad_postgres_1
            DB_NAME: etherpad
            DB_PASS: admin
            DB_PORT: 5432
            DB_TYPE: postgres
            DB_USER: admin
            DEFAULT_PAD_TEXT: null
            DISABLE_IP_LOGGING: "false"
            LOGLEVEL: INFO
            NODE_ENV: production
            SHOW_SETTINGS_IN_ADMIN_PAGE: "true"
            SKIN_NAME: colibris
            SKIN_VARIANTS: super-light-toolbar super-light-editor light-background
            SOFFICE: null
            SUPPRESS_ERRORS_IN_PAD_TEXT: "false"
            TRUST_PROXY: "true"
        image: etherpad/etherpad:2.7.3@sha256:e277b0f025bf4ff7039a8f3cc9d2995d65a071c4734c30c930a563202e32b0b0
        ports:
            - 9002:9001
        restart: on-failure
        user: "5001:0"
        volumes:
            - /DATA/PowerLabAppData/etherpad/data/plugins:/opt/etherpad-lite/src/plugin_packages
            - /DATA/PowerLabAppData/etherpad/data/etherpad-var:/opt/etherpad-lite/var:rw
    postgres:
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: etherpad
            POSTGRES_PASSWORD: admin
            POSTGRES_PORT: 5432
            POSTGRES_USER: admin
        image: postgres:15-alpine@sha256:93a6166360be8f1d116b7ea97ebb8dea9e2c9c746349e952738bbba72a961d7c
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/etherpad/data/postgres_data:/var/lib/postgresql/data/pgdata
version: "3.7"

x-powerlab:
    store_app_id: etherpad
    title:
        en_us: Etherpad
    tagline:
        en_us: An intuitive tool for real-time collaborative writing
    icon: https://getumbrel.github.io/umbrel-apps-gallery/etherpad/icon.svg
    category: files
    port_map: "9002"
    author: The Etherpad Foundation
    developer: The Etherpad Foundation
    source:
        catalog: umbrel-apps
        upstream_id: etherpad
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: etherpad/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:42:55Z"
