name: esphome
services:
    server:
        image: esphome/esphome:2026.4.5@sha256:c7bfa0bea64c68d5ca645b37cf98125c248a494c0f339a13fbc918f559628feb
        network_mode: host
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/esphome/data:/config
version: "3.7"

x-powerlab:
    store_app_id: esphome
    title:
        en_us: ESPHome
    tagline:
        en_us: Intelligently manage all your ESP8266/ESP32 devices
    description:
        en_us: 'ESPHome [](https://discord.gg/KhAMKrd) [](https://GitHub.com/esphome/esphome/releases/) [](https://codspeed.io/esphome/esphome) <a href="https://esphome.io/"> <picture> <source media="(prefers-color-scheme: dark)" srcset="https://media.esphome.io/logo/logo-text-on-dark.svg"> <img src="https://media.esphome.io/logo/logo-text-on-light.svg" alt="ESPHome Logo"> </picture> </a> Documentation -- Issues -- Feature requests [](https://www.openhomefoundation.org/)'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/esphome/icon.svg
    category: automation
    port_map: "6052"
    author: ESPHome
    developer: ESPHome
    source:
        catalog: umbrel-apps
        upstream_id: esphome
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: esphome/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:10Z"
