name: linkstack
services:
    linkstack:
        hostname: linkstack
        image: linkstackorg/linkstack:latest@sha256:1c8b05399ee459ac601bac3eede7fbe765d1b6b7be725663b57f3220610958bf
        ports:
            - 8190:80
        restart: on-failure
        volumes:
            - linkstack_data:/htdocs
version: "3.7"
volumes:
    linkstack_data:
        driver: local
        driver_opts:
            device: ${APP_DATA_DIR}/data
            o: bind
            type: none

x-powerlab:
    store_app_id: linkstack
    title:
        en_us: LinkStack
    tagline:
        en_us: A highly customizable link sharing platform
    description:
        en_us: '<p align="center"> <img width="200px" src="https://raw.githubusercontent.com/LinkStackOrg/branding/main/logo/svg/logo_animated.svg"><br> <br> <picture> <source media="(prefers-color-scheme: dark)" width="400px" srcset="https://raw.githubusercontent.com/LinkStackOrg/branding/main/logo/png/wordmark_light.png"> <img width="400px" src="https://raw.githubusercontent.com/LinkStackOrg/branding/main/logo/png/wordmark_dark.png"> </picture> </p> <h3 align="center"><b>Open-Source Linktree Alternative</b></h3> <h3 align="center">LinkStack is a highly customizable link sharing platform<br>with an intuitive, easy to use user interface.</h3> <br> <p align="center"> <a href="#Function">Function</a> • <a href="#About">About</a> • <a href="#Instances">Instances</a> • <a href="#Themes">Themes</a> • <a href="#Installation">Installation</a> • <a href="#Docker">Docker Version</a> • <a href="#Updating">Updating</a> • <a href="#Discord">Discord</a> • <a href="#Fork-Structure">Fork structure</a> • <a href="#License">License</a> • <a href="#Supporters">Supporters</a> • <a href="#Special-thanks">Special thanks</a> • <a href="#Additional-credit">Additional credit</a> </p> <p align="center"> <a href="https://github.com/linkstackorg/linkstack/stargazers"><img alt="GitHub Repo stars" src="https://img.tny.st/github/stars/julianprieber/littlelink-custom?label=Star%20the%20project&logo=GitHub"></a> <a href="https://mstdn.social/@linkstack"><img alt="Mastodon Follow" src="https://img.tny.st/mastodon/follow/110147874401985724?domain=http%3A%2F%2Fmstdn.social&style=social"></a> <a href="https://discord.linkstack.org"><img alt="Discord online user count" src="https://img.tny.st/discord/955765706111193118?color=4A55CC&label=Discord&logo=Discord&style=flat"></a> </p> <p align="center"> <a href="https://github.com/sponsors/julianprieber"><img alt="GitHub spomsors" src="https://img.tny.st/github/sponsors/JulianPrieber?color=BF4B8A&logo=githubsponsors&style=flat&label=Sponsor%20us%20on%20Github"></a> <a href="https://patreon.com/julianprieber"><img alt="Patreon" src="https://img.tny.st/endpoint.svg?url=https%3A%2F%2Fshieldsio-patreon.vercel.app%2Fapi%3Fusername%3Djulianprieber%26type%3Dpatrons&style=flat&logo=patreon"></a> <a href="https://liberapay.com/LinkStack"><img src="https://img.tny.st/liberapay/patrons/LinkStack?logo=liberapay&label=LiberaPay%20patrons"></a> </p> <p align="center"> <a href="https://github.com/linkstackorg/linkstack/releases/latest/download/linkstack.zip"><img src="https://raw.githubusercontent.com/LinkStackOrg/branding/main/badges/png/download_latest.png" alt="Download latest" width="380" ></a> <br> <a href="https://github.com/linkstackorg/linkstack/releases"><img alt="GitHub release (latest by date)" src="https://img.tny.st/github/v/release/JulianPrieber/LittleLink-Custom?label=Latest%20release"></a> </p> <a name="Function"></a> Function LinkStack: The Ultimate Link Management Solution LinkStack is a unique platform that provides an efficient solution for managing and sharing links online. Our platform offers a website similar to Linktree, which allows users to overcome the limitation of only being able to add one link on social media platforms. With LinkStack, users can easily link to their own custom…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/linkstack/icon.svg
    category: files
    port_map: "8190"
    author: Julian Prieber
    developer: Julian Prieber
    source:
        catalog: umbrel-apps
        upstream_id: linkstack
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: linkstack/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:43:15Z"
