name: snowflake
services:
    proxy:
        command: -log /data/snowflake.log -verbose
        image: thetorproject/snowflake-proxy:v2.13.1@sha256:82f80dd23899d07ead4069c7b94b65636b6757586bf5d7d65f5ec45b05d554df
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/snowflake/data:/data
    web:
        command: gotty --port 3800 --index "/snowflake/index.html" --title-format "Tor Snowflake Proxy" bash -c 'tail -n 10000 -f /snowflake/snowflake.log | grep "Traffic Relayed"'
        image: sorenisanerd/gotty:v1.6.0@sha256:23b4669973e96d8d7d37b3bfd9e6566bdd701aa1a56eee2dc0e0362bd927ed88
        ports:
            - 3800:3800
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/snowflake/data:/snowflake
version: "3.7"

x-powerlab:
    store_app_id: snowflake
    title:
        en_us: Tor Snowflake Proxy
    tagline:
        en_us: Help defeat internet censorship
    icon: https://getumbrel.github.io/umbrel-apps-gallery/snowflake/icon.svg
    category: networking
    port_map: "3800"
    author: The Tor Project, Inc.
    developer: The Tor Project, Inc.
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: snowflake
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: snowflake/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:57Z"
