version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bentopdf_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/alam00000/bentopdf:v2.8.4@sha256:f54b9ed9c56b767e0098b525468206689b666323c2b500b9686c3cf41cdfa348
    restart: on-failure

x-powerlab:
    store_app_id: bentopdf
    title:
        en_us: BentoPDF
    tagline:
        en_us: A Privacy First PDF Toolkit
    description:
        en_us: "<p align=\"center\"><img src=\"public/images/favicon-no-bg.svg\" width=\"80\"></p> <h1 align=\"center\">BentoPDF</h1> <p align=\"center\"> <a href=\"https://www.digitalocean.com/?refcode=d93c189ef6d0&utm_campaign=Referral_Invite&utm_medium=Referral_Program&utm_source=badge\"> <img src=\"https://web-platforms.sfo2.cdn.digitaloceanspaces.com/WWW/Badge%203.svg\" alt=\"DigitalOcean Referral Badge\"> </a> </p> **BentoPDF** is a powerful, privacy-first, client-side PDF toolkit that is self hostable and allows you to manipulate, edit, merge, and process PDF files directly in your browser. No server-side processing is required, ensuring your files remain secure and private. [](https://github.com/alam00000/bentopdf/pkgs/container/bentopdf) [](https://ko-fi.com/alio01) [](https://github.com/sponsors/alam00000) FOSS Hack 2026 [](https://drive.google.com/file/d/14Vf62PvHiuf1RKFKtMlAzpbf4QQPLpRF/view?usp=sharing) Table of Contents - Join Us on Discord - Documentation - Licensing - Stargazers over time - Thank You to Our Sponsors - Why BentoPDF? - Features / Tools Supported - Organize & Manage PDFs - Edit & Modify PDFs - Convert to PDF - Convert from PDF - Secure & Optimize PDFs - Translations - Getting Started - Prerequisites - Quick Start - Static Hosting - Self-Hosting Locally - Docker Compose / Podman Compose - Podman Quadlet - Simple Mode - Custom Branding - Disabling Specific Tools - WASM Configuration - Air-Gapped / Offline Deployment - Security Features - Digital Signature CORS Proxy - Version Management - Development Setup - Tech Stack & Background - Roadmap - Contributing - Special Thanks \U0001F4E2 Join Us on Discord [](https://discord.gg/Bgq3Ay3f2w) Have questions, feature requests, or want to chat with…"
    icon: https://getumbrel.github.io/umbrel-apps-gallery/bentopdf/icon.svg
    category: files
    port_map: "8730"
    author: BentoPDF
    developer: BentoPDF
    source:
        catalog: umbrel-apps
        upstream_id: bentopdf
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 0299c400450d07fee62d3dcb0e6c24b00f359b51
        upstream_path: bentopdf/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T03:53:04Z"
