name: fizzy
services:
    server:
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 512M
        environment:
            ACTIVE_STORAGE_SERVICE: local
            ASSUME_SSL: "false"
            DATABASE_ADAPTER: sqlite
            FORCE_SSL: "false"
            RAILS_ENV: production
            SECRET_KEY_BASE: ${APP_SEED}
            SOLID_QUEUE_IN_PUMA: "true"
        image: ghcr.io/mauricewipf/fizzy-umbrel:754aaa5@sha256:3c74a27d749db915c76654bf7590b4d2eee5eeb9cb495e23a52ebe3c51b5e372
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/fizzy/data/app:/rails/storage
version: "3.7"

x-powerlab:
    store_app_id: fizzy
    title:
        en_us: Fizzy
    tagline:
        en_us: Kanban as it should be. Not as it has been.
    description:
        en_us: Fizzy This is the source code of Fizzy, the Kanban tracking tool for issues and ideas by 37signals. Running your own Fizzy instance If you want to run your own Fizzy instance, but don't need to change its code, you can use our pre-built Docker image. You'll need access to a server on which you can run Docker, and you'll need to configure some options to customize your installation. You can find the details of how to do a Docker-based deployment in our Docker deployment guide. If you want more flexibility to customize your Fizzy installation by changing its code, and deploy those changes to your server, then we recommend you deploy Fizzy with Kamal. You can find a complete walkthrough of doing that in our Kamal deployment guide. Development You are welcome -- and encouraged -- to modify Fizzy to your liking. Please see our Development guide for how to get Fizzy set up for local development. Contributing We welcome contributions! Please read our style guide before submitting code. License Fizzy is released under the O'Saasy License.
    icon: https://getumbrel.github.io/umbrel-apps-gallery/fizzy/icon.svg
    category: social
    port_map: "8005"
    author: 37signals
    developer: 37signals
    source:
        catalog: umbrel-apps
        upstream_id: fizzy
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: fizzy/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:11Z"
