name: audiobookshelf
services:
    web:
        environment:
            - CONFIG_PATH=/home/node/config
            - METADATA_PATH=/home/node/metadata
            - AUDIOBOOKSHELF_UID=1000
            - AUDIOBOOKSHELF_GID=1000
        healthcheck:
            disable: true
        image: ghcr.io/advplyr/audiobookshelf:2.34.0@sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4
        init: true
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/audiobookshelf/data/config:/home/node/config
            - /DATA/PowerLabAppData/audiobookshelf/data/metadata:/home/node/metadata
            - ${UMBREL_ROOT}/data/storage/downloads/audiobooks:/audiobooks
            - ${UMBREL_ROOT}/data/storage/downloads/podcasts:/podcasts
version: "3.7"

x-powerlab:
    store_app_id: audiobookshelf
    title:
        en_us: Audiobookshelf
    tagline:
        en_us: Audiobook and podcast server
    icon: https://getumbrel.github.io/umbrel-apps-gallery/audiobookshelf/icon.svg
    category: media
    port_map: "13378"
    author: advplyr
    developer: advplyr
    source:
        catalog: umbrel-apps
        upstream_id: audiobookshelf
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: audiobookshelf/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:07Z"
