name: akaunting
services:
    app:
        depends_on:
            - db
        environment:
            ADMIN_EMAIL: umbrel@umbrel.local
            ADMIN_PASSWORD: ${APP_PASSWORD}
            AKAUNTING_SETUP: "true"
            COMPANY_EMAIL: my@company.com
            COMPANY_NAME: My Company
            DB_HOST: db
            DB_NAME: akaunting
            DB_PASSWORD: akaunting_password
            DB_PORT: 3306
            DB_PREFIX: asd_
            DB_USERNAME: admin
            LOCALE: en-US
        image: akaunting/akaunting:3.1.21@sha256:918bbc77981e5b96ab6aa6838491cfa7c98cb4ee7bbf9532ee083e7e66d04255
        ports:
            - 8773:80
        restart: on-failure
    db:
        environment:
            MYSQL_DATABASE: akaunting
            MYSQL_PASSWORD: akaunting_password
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: admin
        image: mariadb:11.8.2@sha256:2bcbaec92bd9d4f6591bc8103d3a8e6d0512ee2235506e47a2e129d190444405
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/akaunting/db:/var/lib/mysql
version: "3.7"

x-powerlab:
    store_app_id: akaunting
    title:
        en_us: Akaunting
    tagline:
        en_us: An intuitive accounting solution for small businesses and freelancers
    icon: https://getumbrel.github.io/umbrel-apps-gallery/akaunting/icon.svg
    category: finance
    port_map: "8773"
    author: Akaunting Inc.
    developer: Akaunting Inc.
    main: app
    source:
        catalog: umbrel-apps
        upstream_id: akaunting
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: akaunting/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:26:30Z"
