name: wireguard
services:
    app:
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            WG_HOST: '*'
        image: ghcr.io/wg-easy/wg-easy:14@sha256:f6c2587da3fdc9d5927743fb4a92cff42d690b182396ffd0cdad034becb41053
        ports:
            - 51820:51820/udp
        restart: on-failure
        stop_grace_period: 1m
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        volumes:
            - /DATA/PowerLabAppData/wireguard/data/wireguard:/etc/wireguard
version: "3.7"

x-powerlab:
    store_app_id: wireguard
    title:
        en_us: WireGuard
    tagline:
        en_us: Run your own free and unlimited WireGuard VPN
    icon: https://getumbrel.github.io/umbrel-apps-gallery/wireguard/icon.svg
    category: networking
    port_map: "51821"
    author: Emile Nijssen
    developer: Emile Nijssen
    main: app
    source:
        catalog: umbrel-apps
        upstream_id: wireguard
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: wireguard/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:14:03Z"
