name: wireguard
services:
    app:
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            WG_HOST: ${DEVICE_DOMAIN_NAME}
        image: ghcr.io/wg-easy/wg-easy:14@sha256:f6c2587da3fdc9d5927743fb4a92cff42d690b182396ffd0cdad034becb41053
        ports:
            - 51820:51820/udp
        restart: on-failure
        stop_grace_period: 1m
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        volumes:
            - /DATA/PowerLabAppData/wireguard/data/wireguard:/etc/wireguard
version: "3.7"

x-powerlab:
    store_app_id: wireguard
    title:
        en_us: WireGuard
    tagline:
        en_us: Run your own free and unlimited WireGuard VPN
    icon: https://getumbrel.github.io/umbrel-apps-gallery/wireguard/icon.svg
    category: networking
    port_map: "51821"
    author: Emile Nijssen
    developer: Emile Nijssen
    source:
        catalog: umbrel-apps
        upstream_id: wireguard
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: wireguard/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:27Z"
