version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ghostfolio_server_1
      APP_PORT: 3334

  server:
    image: ghostfolio/ghostfolio:3.2.0@sha256:bc734d99774c2e168d8f3241c816ae3df2851d2014b7a0bf241bc7df412e01ab
    init: true
    restart: on-failure
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3334
      ACCESS_TOKEN_SALT: $APP_GHOSTFOLIO_ACCESS_TOKEN_SALT
      DATABASE_URL: postgresql://${APP_GHOSTFOLIO_DB_USERNAME}:${APP_GHOSTFOLIO_DB_PASSWORD}@ghostfolio_postgres_1:5432/${APP_GHOSTFOLIO_DB_DATABASE_NAME}
      JWT_SECRET_KEY: ${APP_SEED}
      POSTGRES_DB: ${APP_GHOSTFOLIO_DB_DATABASE_NAME}
      POSTGRES_USER: ${APP_GHOSTFOLIO_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_GHOSTFOLIO_DB_PASSWORD}
      REDIS_HOST: ghostfolio_redis_1
      REDIS_PASSWORD: ${APP_GHOSTFOLIO_REDIS_PASSWORD}
      REDIS_PORT: 6379

  postgres:
    image: postgres:14-bullseye@sha256:c2a30d08a6f9e6c365595fd086c9e0436064c52425f15f72379ecf0807bac518
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    environment:
      POSTGRES_USER: ${APP_GHOSTFOLIO_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_GHOSTFOLIO_DB_PASSWORD}
      POSTGRES_DB: ${APP_GHOSTFOLIO_DB_DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-bullseye@sha256:5cdb2ac6f780e1d250787f4a887c1ed1166e3389757189ea913059409acc6f7c
    restart: on-failure
    user: "1000:1000"
    command: >
      --requirepass ${APP_GHOSTFOLIO_REDIS_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

x-powerlab:
    store_app_id: ghostfolio
    title:
        en_us: Ghostfolio
    tagline:
        en_us: Manage your wealth like a boss
    description:
        en_us: "<div align=\"center\"> <img src=\"https://avatars.githubusercontent.com/u/82473144?s=200\" width=\"100\" alt=\"Ghostfolio logo\"> Ghostfolio **Open Source Wealth Management Software** **Ghostfol.io** | **Live Demo** | **Ghostfolio Premium** | **FAQ** | **Blog** | **LinkedIn** | **Slack** | **X** [](https://www.buymeacoffee.com/ghostfolio) [](#contributing) [](https://hub.docker.com/r/ghostfolio/ghostfolio) [](https://www.gnu.org/licenses/agpl-3.0) </div> **Ghostfolio** is an open source wealth management software built with web technology. The application empowers busy people to keep track of stocks, ETFs or cryptocurrencies and make solid, data-driven investment decisions. The software is designed for personal use in continuous operation. <div align=\"center\"> <img src=\"./apps/client/src/assets/images/video-preview.jpg\" width=\"600\" alt=\"Preview image of the Ghostfolio video trailer\"> </div> Ghostfolio Premium Our official **Ghostfolio Premium** cloud offering is the easiest way to get started. Due to the time it saves, this will be the best option for most people. Revenue is used to cover operational costs for the hosting infrastructure and professional data providers, and to fund ongoing development. If you prefer to run Ghostfolio on your own infrastructure, please find further instructions in the Self-hosting section. Why Ghostfolio? Ghostfolio is for you if you are... - \U0001F4BC trading stocks, ETFs or cryptocurrencies on multiple platforms - \U0001F3E6 pursuing a buy & hold strategy - \U0001F3AF interested in getting insights of your portfolio composition - \U0001F47B valuing privacy and data…"
    icon: https://getumbrel.github.io/umbrel-apps-gallery/ghostfolio/icon.svg
    category: finance
    port_map: "3334"
    author: Ghostfolio
    developer: Ghostfolio
    source:
        catalog: umbrel-apps
        upstream_id: ghostfolio
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 0299c400450d07fee62d3dcb0e6c24b00f359b51
        upstream_path: ghostfolio/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T03:53:07Z"
