name: heimdall
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        image: linuxserver/heimdall:2.7.6@sha256:30c32fb4ebe54282b6e60cb0232f57d5fcda60d87a9b7e9a4d1ef71ad636817d
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/heimdall/config:/config
version: "3.7"

x-powerlab:
    store_app_id: heimdall
    title:
        en_us: Heimdall
    tagline:
        en_us: Organize your most used web sites in a simple way
    icon: https://getumbrel.github.io/umbrel-apps-gallery/heimdall/icon.svg
    category: files
    port_map: "7392"
    author: LinuxServer.io
    developer: LinuxServer.io
    source:
        catalog: umbrel-apps
        upstream_id: heimdall
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: heimdall/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:07Z"
