name: grafana
services:
    web:
        image: grafana/grafana:13.0.1-security-01@sha256:2d1f9ae67c1778d33e291d4c3c759cd8b650e67491f02533499eb950e075eeb5
        ports:
            - 3030:3000
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/grafana/data:/var/lib/grafana
version: "3.7"

x-powerlab:
    store_app_id: grafana
    title:
        en_us: Grafana
    tagline:
        en_us: The open-source platform for monitoring and observability
    description:
        en_us: 'The open-source platform for monitoring and observability [](LICENSE) [](https://goreportcard.com/report/github.com/grafana/grafana) Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored. Create, explore, and share dashboards with your team and foster a data-driven culture: - **Visualizations:** Fast and flexible client side graphs with a multitude of options. Panel plugins offer many different ways to visualize metrics and logs. - **Dynamic Dashboards:** Create dynamic & reusable dashboards with template variables that appear as dropdowns at the top of the dashboard. - **Explore Metrics:** Explore your data through ad-hoc queries and dynamic drilldown. Split view and compare different time ranges, queries and data sources side by side. - **Explore Logs:** Experience the magic of switching from metrics to logs with preserved label filters. Quickly search through all your logs or streaming them live. - **Alerting:** Visually define alert rules for your most important metrics. Grafana will continuously evaluate and send notifications to systems like Slack, PagerDuty, VictorOps, OpsGenie. - **Mixed Data Sources:** Mix different data sources in the same graph! You can specify a data source on a per-query basis. This works for even custom datasources. Get started - Get Grafana - Installation guides Unsure if…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/grafana/icon.svg
    category: networking
    port_map: "3030"
    author: Grafana Labs
    developer: Grafana Labs
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: grafana
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: grafana/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:36Z"
