name: pocketbase
services:
    app:
        image: ghcr.io/muchobien/pocketbase:0.38.0@sha256:254d5f14ca43ce3201b39e1f88faa95d710574a136a8c73d174be0e4c0edc6b6
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/pocketbase/data/data:/pb_data
            - /DATA/PowerLabAppData/pocketbase/data/public:/pb_public
            - /DATA/PowerLabAppData/pocketbase/data/hooks:/pb_hooks
            - /DATA/PowerLabAppData/pocketbase/data/migrations:/pb_migrations
version: "3.7"

x-powerlab:
    store_app_id: pocketbase
    title:
        en_us: PocketBase
    tagline:
        en_us: Open Source backend for your next SaaS and Mobile app in 1 file
    icon: https://getumbrel.github.io/umbrel-apps-gallery/pocketbase/icon.svg
    category: developer
    port_map: "5400"
    author: PocketBase
    developer: PocketBase
    source:
        catalog: umbrel-apps
        upstream_id: pocketbase
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: pocketbase/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:21Z"
