name: wavelog
services:
    app:
        depends_on:
            - wavelog-db
        environment:
            CI_ENV: docker
        image: ghcr.io/wavelog/wavelog:2.4.2@sha256:4df7277277b7e601852b1a8905273eca6b67c1b4a4eb91da408e5f90e97f8886
        volumes:
            - /DATA/PowerLabAppData/wavelog/data/config:/var/www/html/application/config/docker
            - /DATA/PowerLabAppData/wavelog/data/uploads:/var/www/html/uploads
            - /DATA/PowerLabAppData/wavelog/data/userdata:/var/www/html/userdata
    wavelog-db:
        environment:
            MARIADB_DATABASE: wavelog
            MARIADB_PASSWORD: wavelog
            MARIADB_RANDOM_ROOT_PASSWORD: "yes"
            MARIADB_USER: wavelog
        image: mariadb:11.4@sha256:39596f079862334be04f4231664862e55d4febe54309cc62f750f2297de85b06
        volumes:
            - /DATA/PowerLabAppData/wavelog/data/db:/var/lib/mysql
version: "3.7"

x-powerlab:
    store_app_id: wavelog
    title:
        en_us: Wavelog
    tagline:
        en_us: Amateur radio logging software
    icon: https://getumbrel.github.io/umbrel-apps-gallery/wavelog/icon.svg
    category: social
    port_map: "8099"
    author: DF2ET, DJ7NT, HB9HIL, LA8AJA
    developer: DF2ET, DJ7NT, HB9HIL, LA8AJA
    source:
        catalog: umbrel-apps
        upstream_id: wavelog
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: wavelog/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:26Z"
