name: zigbee2mqtt
services:
    app:
        environment:
            Z2M_ONBOARD_NO_REDIRECT: 1
            ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
            ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
            ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto_broker_1:1883
        image: koenkk/zigbee2mqtt:2.10.1@sha256:67c26dcf8346aced02fe1380a6afd1b57268bcef10faae3f6057c13d5d3dfa80
        ports:
            - 60082:8080
        privileged: true
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/zigbee2mqtt/data:/app/data:rw
            - /run/udev:/run/udev:ro

x-powerlab:
    store_app_id: zigbee2mqtt
    title:
        en_us: Zigbee2MQTT
    tagline:
        en_us: Zigbee to MQTT bridge, get rid of your proprietary Zigbee bridges
    icon: https://getumbrel.github.io/umbrel-apps-gallery/zigbee2mqtt/icon.svg
    category: automation
    port_map: "60082"
    author: '@Koenkk'
    developer: '@Koenkk'
    main: app
    source:
        catalog: umbrel-apps
        upstream_id: zigbee2mqtt
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: zigbee2mqtt/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:27:07Z"
