[app]
PAGE_SIZE = 10
RuntimeRootPath = runtime/
LogPath = local_data/log/casaos/
LogSaveName = log
LogFileExt = log
DateStrFormat = 20060102
DateTimeFormat = 2006-01-02 15:04:05
TimeFormat = 15:04:05
DateFormat = 2006-01-02
DBPath     = local_data/lib/casaos
ShellPath  = local_data/share/casaos/shell
UserDataPath = local_data/lib/casaos/conf

[server]
RunMode = release
ServerApi = https://api.casaos.io/casaos-api
Handshake = socket.casaos.io
Token = 
USBAutoMount =

[system]

[common]
RuntimePath=/var/run/casaos