name: syncthing
services:
    server:
        environment:
            - PUID=1000
            - PGID=1000
        hostname: umbrel
        image: syncthing/syncthing:2.1.0@sha256:7c60eb0ec887696c8684de88aea2dfe39a7391184b29d33c0aad778c99c7683e
        ports:
            - 22000:22000/tcp
            - 22000:22000/udp
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/syncthing/data:/var/syncthing
version: "3.7"

x-powerlab:
    store_app_id: syncthing
    title:
        en_us: Syncthing
    tagline:
        en_us: Peer-to-peer file synchronization between your devices
    description:
        en_us: '[![Syncthing][14]][15] [](https://www.mozilla.org/MPL/2.0/) [](https://bestpractices.coreinfrastructure.org/projects/88) [](https://goreportcard.com/report/github.com/syncthing/syncthing) Goals Syncthing is a **continuous file synchronization program**. It synchronizes files between two or more computers. We strive to fulfill the goals below. The goals are listed in order of importance, the most important ones first. This is the summary version of the goal list - for more commentary, see the full [Goals document][13]. Syncthing should be: 1. **Safe From Data Loss** Protecting the user''s data is paramount. We take every reasonable precaution to avoid corrupting the user''s files. 2. **Secure Against Attackers** Again, protecting the user''s data is paramount. Regardless of our other goals, we must never allow the user''s data to be susceptible to eavesdropping or modification by unauthorized parties. 3. **Easy to Use** Syncthing should be approachable, understandable, and inclusive. 4. **Automatic** User interaction should be required only when absolutely necessary. 5. **Universally Available** Syncthing should run on every common computer. We are mindful that the latest technology is not always available to every individual. 6. **For Individuals** Syncthing is primarily about empowering the individual user with safe, secure, and easy to use file synchronization. 7. **Everything Else** There are many things we care about that don''t make it on to the list.…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/syncthing/icon.svg
    category: files
    port_map: "8384"
    author: The Syncthing Foundation
    developer: The Syncthing Foundation
    main: server
    source:
        catalog: umbrel-apps
        upstream_id: syncthing
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: syncthing/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:27:02Z"
