name: homebridge
services:
    server:
        image: homebridge/homebridge:2026-05-10@sha256:0783bf37e5b7681e515f95998f7084505596e176ca8ddacce4a7d034bf2c71cd
        network_mode: host
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/homebridge/data/homebridge:/homebridge
version: "3.7"

x-powerlab:
    store_app_id: homebridge
    title:
        en_us: Homebridge
    tagline:
        en_us: HomeKit support for the impatient
    icon: https://getumbrel.github.io/umbrel-apps-gallery/homebridge/icon.svg
    category: automation
    port_map: "8581"
    author: Homebridge
    developer: Homebridge
    source:
        catalog: umbrel-apps
        upstream_id: homebridge
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: homebridge/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:38Z"
