name: invidious
services:
    companion:
        cap_drop:
            - ALL
        environment:
            - SERVER_SECRET_KEY=${APP_INV_SECRET_KEY}
        image: quay.io/invidious/invidious-companion:master-6c76cab@sha256:aaec4e18b3cffb5457633f427c834299677f2c2a7e27b598404ab815643c3747
        read_only: true
        restart: on-failure
        security_opt:
            - no-new-privileges:true
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/invidious/data/companioncache:/var/tmp/youtubei.js:rw
    postgres:
        environment:
            POSTGRES_DB: invidious
            POSTGRES_PASSWORD: moneyprintergobrrr
            POSTGRES_USER: umbrel
        image: postgres:13.7@sha256:03652c675ae177af98ddd50f9f4b4b2cf8ad38d0e116aa68fe670fbc2cf250fc
        init: true
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/invidious/data/db:/var/lib/postgresql/data
    web:
        depends_on:
            - postgres
        environment:
            INVIDIOUS_CONFIG: |
                db:
                  dbname: invidious
                  user: umbrel
                  password: moneyprintergobrrr
                  host: postgres
                  port: 5432
                check_tables: true
                invidious_companion:
                - private_url: "http://companion:8282/companion"
                invidious_companion_key: ${APP_INV_SECRET_KEY}
                hmac_key: ${APP_SEED}
                default_user_preferences:
                  feed_menu: ["Trending", "Subscriptions", "Playlists"]
                  default_home: Trending
        healthcheck:
            disable: true
        image: ceramicwhite/invidious:build-fda8d1b@sha256:39fe17102eb65ff34ac83e4d2b7f4233e735c1221e3c881fd0e0919b78760f81
        ports:
            - 3420:3000
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
version: "3.7"

x-powerlab:
    store_app_id: invidious
    title:
        en_us: Invidious
    tagline:
        en_us: Browse YouTube without tracking or ads
    icon: https://getumbrel.github.io/umbrel-apps-gallery/invidious/icon.svg
    category: social
    port_map: "3420"
    author: IV-Org
    developer: IV-Org
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: invidious
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: invidious/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:26:42Z"
