name: urbit
services:
    manager:
        environment:
            APP_PASSWORD: ${APP_PASSWORD}
        image: mopfelwinrux/urbit-umbrel:v4.3@sha256:91f4ae90f4ed5721de4b9389bc13d79627b52d11d5d8afa08802088f6e65d06d
        ports:
            - 34343:34343
        volumes:
            - /DATA/PowerLabAppData/urbit/piers:/data/piers
            - /DATA/PowerLabAppData/urbit/keys:/data/keys
version: "3.7"

x-powerlab:
    store_app_id: urbit
    title:
        en_us: Urbit
    tagline:
        en_us: Run Urbit on your Umbrel
    description:
        en_us: 'Urbit on Umbrel This is a repository for running an Urbit Pier on Umbrel Install on Umbrel To install on umbrel for testing 1. Make a directory for the yaml script: 2. cd into the umbrel directory: 3. Run the install app script: 4. Navigate to http://umbrel.local:8090/launch to view the control screen. Once your pier is booted landscape is acessible at http://umbrel.local:8090'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/urbit/icon.svg
    category: networking
    port_map: "8090"
    author: ~mopfel-winrux & ~sitful-hatred
    developer: ~mopfel-winrux & ~sitful-hatred
    main: manager
    source:
        catalog: umbrel-apps
        upstream_id: urbit
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 931a2146a30e8398b127434cf4fd2f20ae77bb4f
        upstream_path: urbit/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-13T17:27:04Z"
