name: scanservjs
services:
    server:
        image: sbs20/scanservjs:v3.0.4@sha256:e42263444a8dd5d533ead7d9eb2ef5fd9ca7a4a80569a6f9c14b7a3c21b9c7ca
        ports:
            - 2903:8080
        privileged: true
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/scanservjs/data/scans:/var/lib/scanservjs/output
            - /DATA/PowerLabAppData/scanservjs/data/config:/etc/scanservjs
            - /var/run/dbus:/var/run/dbus
            - /dev:/dev
version: "3.7"

x-powerlab:
    store_app_id: scanservjs
    title:
        en_us: scanservjs
    tagline:
        en_us: Web-based interface for your SANE-compatible scanners
    icon: https://getumbrel.github.io/umbrel-apps-gallery/scanservjs/icon.svg
    category: files
    port_map: "2903"
    author: sbs20
    developer: sbs20
    main: server
    source:
        catalog: umbrel-apps
        upstream_id: scanservjs
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: scanservjs/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:56Z"
