name: sabnzbd
services:
    web:
        environment:
            - DOCKER_MODS=linuxserver/mods:universal-package-install
            - INSTALL_PACKAGES=ffmpeg
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        image: linuxserver/sabnzbd:5.0.1@sha256:87c97fa81966adb5cf511ae62b6681a37136c32f1ad7190b0b8b4d12d766ea9f
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/sabnzbd/data/config:/config
            - /DATA/data/storage/downloads:/downloads
version: "3.7"

x-powerlab:
    store_app_id: sabnzbd
    title:
        en_us: SABnzbd
    tagline:
        en_us: The automated Usenet download tool
    icon: https://getumbrel.github.io/umbrel-apps-gallery/sabnzbd/icon.svg
    category: networking
    port_map: "9876"
    author: sabnzbd
    developer: sabnzbd
    source:
        catalog: umbrel-apps
        upstream_id: sabnzbd
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: sabnzbd/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:45Z"
