name: searxng
services:
    web:
        container_name: searxng-web
        environment:
            SEARXNG_LIMITER: "false"
            SEARXNG_SECRET: ${APP_SEED}
        image: ghcr.io/searxng/searxng:2026.4.7-08ef7a63d@sha256:6a89a150d0163877caab1982b7a20d0a03fd4b39401a0d3f26f61ad205949442
        restart: on-failure
        volumes:
            - /DATA/PowerLabAppData/searxng/data/config:/etc/searxng
            - /DATA/PowerLabAppData/searxng/data/cache:/var/cache/searxng
version: "3.7"

x-powerlab:
    store_app_id: searxng
    title:
        en_us: SearXNG
    tagline:
        en_us: A free internet metasearch engine
    icon: https://getumbrel.github.io/umbrel-apps-gallery/searxng/icon.svg
    category: networking
    port_map: "8182"
    author: SearXNG
    developer: SearXNG
    source:
        catalog: umbrel-apps
        upstream_id: searxng
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: searxng/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:47Z"
