name: docuseal
services:
    db:
        environment:
            POSTGRES_DB: docuseal
            POSTGRES_PASSWORD: docusealpass
            POSTGRES_USER: docusealuser
        image: postgres:17.3@sha256:0321e2252ebfeecb8bc1a899755084d29bce872953e1a5a3e25ec0860b739098
        restart: on-failure
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/docuseal/data/db:/var/lib/postgresql/data
    server:
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://docusealuser:docusealpass@docuseal_db_1:5432/docuseal?sslmode=disable
        image: docuseal/docuseal:2.5.3@sha256:fa8d01c978fa9d2f51bc8250bfbbbb1ba843bcf198e94c84c62bf9f53f1beaaa
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/docuseal/data/app:/data/docuseal

x-powerlab:
    store_app_id: docuseal
    title:
        en_us: DocuSeal
    tagline:
        en_us: Open source document filling and signing
    description:
        en_us: '<h1 align="center" style="border-bottom: none"> <div> <a href="https://www.docuseal.com"> <img alt="DocuSeal" src="https://github.com/user-attachments/assets/38b45682-ffa4-4919-abde-d2d422325c44" width="80" /> <br> </a> DocuSeal </div> </h1> <h3 align="center"> Open source document filling and signing </h3> <p align="center"> <a href="https://hub.docker.com/r/docuseal/docuseal"> <img alt="Docker releases" src="https://img.shields.io/docker/v/docuseal/docuseal"> </a> <a href="https://discord.gg/qygYCDGck9"> <img src="https://img.shields.io/discord/1125112641170448454?logo=discord"/> </a> <a href="https://twitter.com/intent/follow?screen_name=docusealco"> <img src="https://img.shields.io/twitter/follow/docusealco?style=social" alt="Follow @docusealco" /> </a> </p> <p> DocuSeal is an open source platform that provides secure and efficient digital document signing and processing. Create PDF forms to have them filled and signed online on any device with an easy-to-use, mobile-optimized web tool. </p> <h2 align="center"> <a href="https://demo.docuseal.tech">✨ Live Demo</a> <span>|</span> <a href="https://docuseal.com/sign_up">☁️ Try in Cloud</a> </h2> [](https://demo.docuseal.tech) Features - PDF form fields builder (WYSIWYG) - 12 field types available (Signature, Date, File, Checkbox etc.) - Multiple submitters per document - Automated emails via SMTP - Files storage on disk or AWS S3, Google Storage, Azure Cloud - Automatic PDF eSignature - PDF signature verification - Users management - Mobile-optimized - 7 UI languages with signing available in 14 languages - API and Webhooks for integrations - Easy to deploy in minutes Pro Features - Company logo and white-label - User roles - Automated reminders - Invitation and identity verification via SMS - Conditional fields and formulas -…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/docuseal/icon.svg
    category: files
    port_map: "8387"
    author: docusealco
    developer: docusealco
    source:
        catalog: umbrel-apps
        upstream_id: docuseal
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: docuseal/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:01:57Z"
