name: morphos
services:
    web:
        image: ghcr.io/danvergara/morphos-server:0.6.0@sha256:3d6f64ef386cbb6a7c5d55526e1a69da2d3661a1996d757897e92bf4369088f5
        restart: on-failure
        stop_grace_period: 1m
version: "3.7"

x-powerlab:
    store_app_id: morphos
    title:
        en_us: Morphos server
    tagline:
        en_us: Self-hosted file converter
    description:
        en_us: 'Morphos Server [](https://github.com/danvergara/morphos/releases) <p align="center"> <img style="float: right;" src="screenshots/morphos.jpg" alt="morphos logo"/ width=200> </p> __Self-Hosted file converter server.__ Table of contents - Overview - Installation - Docker - Features - Usage - Supported Files - Images To Images - Images To Documents - Documents To Images - License Overview Today we are forced to rely on third party services to convert files to other formats. This is a serious threat to our privacy, if we use such services to convert files with highly sensitive personal data. It can be used against us, sooner or later. Morphos server aims to solve the problem mentioned above, by providing a self-hosted server to convert files privately. The project provides an user-friendly web UI. For now, Morphos only supports images. Documents will be added soon. Installation Docker Features - Serves a nice web UI - Simple installation (distributed as a Docker image) Usage HTML form Run the server as mentioned above and open up your favorite browser. You''ll see something like this: <img src="screenshots/morphos.png"/> Hit the file input section on the form to upload an image. <img src="screenshots/upload_file_morphos.png"/> You''ll see the filed uploaded in the form. <img src="screenshots/file_uploaded_morphos.png"/> Then, you can select from a variety…'
    icon: https://getumbrel.github.io/umbrel-apps-gallery/morphos/icon.svg
    category: files
    port_map: "3778"
    author: Dan Vergara
    developer: Dan Vergara
    source:
        catalog: umbrel-apps
        upstream_id: morphos
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: morphos/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:24Z"
