name: bitmagnet
services:
    bitmagnet:
        command:
            - worker
            - run
            - --keys=http_server
            - --keys=queue_server
            - --keys=dht_crawler
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            HOME: /tmp
            POSTGRES_HOST: postgres
            POSTGRES_NAME: bitmagnet
            POSTGRES_PASSWORD: ${APP_PASSWORD}
            POSTGRES_USER: postgres
            XDG_CONFIG_HOME: /config
        image: ghcr.io/bitmagnet-io/bitmagnet:v0.10.0@sha256:cf2c16fac5b51f1c18e630b4710175d35d7e44b83012cfd05a2b43712feec05e
        ports:
            - 3336:3334/tcp
            - 3336:3334/udp
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/bitmagnet/data/config:/config/bitmagnet
    postgres:
        environment:
            PGUSER: postgres
            POSTGRES_DB: bitmagnet
            POSTGRES_PASSWORD: ${APP_PASSWORD}
            POSTGRES_USER: postgres
        healthcheck:
            interval: 10s
            start_period: 20s
            test:
                - CMD-SHELL
                - pg_isready
        image: postgres:16-alpine@sha256:23e88eb049fd5d54894d70100df61d38a49ed97909263f79d4ff4c30a5d5fca2
        restart: on-failure
        shm_size: 1g
        user: 1000:1000
        volumes:
            - /DATA/PowerLabAppData/bitmagnet/data/postgres:/var/lib/postgresql/data
version: "3.7"

x-powerlab:
    store_app_id: bitmagnet
    title:
        en_us: Bitmagnet
    tagline:
        en_us: Self-hosted BitTorrent indexer and DHT crawler
    description:
        en_us: bitmagnet A self-hosted BitTorrent indexer, DHT crawler, content classifier and torrent search engine with web UI, GraphQL API and Servarr stack integration. Visit the website at bitmagnet.io.
    icon: https://getumbrel.github.io/umbrel-apps-gallery/bitmagnet/icon.svg
    category: media
    port_map: "3335"
    author: bitmagnet
    developer: bitmagnet
    main: bitmagnet
    source:
        catalog: umbrel-apps
        upstream_id: bitmagnet
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: bitmagnet/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:29Z"
