name: uptime-kuma
services:
    server:
        image: louislam/uptime-kuma:2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/uptime-kuma/data/uptime-kuma:/app/data
version: "3.7"

x-powerlab:
    store_app_id: uptime-kuma
    title:
        en_us: Uptime Kuma
    tagline:
        en_us: Self-hosted uptime monitoring tool
    icon: https://getumbrel.github.io/umbrel-apps-gallery/uptime-kuma/icon.svg
    category: networking
    port_map: "8385"
    author: Louis Lam
    developer: Louis Lam
    source:
        catalog: umbrel-apps
        upstream_id: uptime-kuma
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: uptime-kuma/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T15:02:56Z"
