package config

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
)

// PruneOrphanCuratedApps removes app directories from <catalogDir>/Apps/
// that are not listed in the bundled curated manifest. Tests cover the
// matrix of manifest+Apps state combinations the migration sees in the
// wild (issue #450 — Sprint 22 cut the curated set 241 → 4 but on-disk
// state survived the install on upgraded boxes).

func writeManifest(t *testing.T, catalogDir string, names ...string) {
	t.Helper()
	body := ""
	for _, n := range names {
		body += n + "\n"
	}
	if err := os.WriteFile(filepath.Join(catalogDir, curatedManifestFilename), []byte(body), 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}
}

func mkAppDir(t *testing.T, catalogDir, name string) {
	t.Helper()
	d := filepath.Join(catalogDir, "Apps", name)
	if err := os.MkdirAll(d, 0o755); err != nil {
		t.Fatalf("mkdir %q: %v", d, err)
	}
	// Drop a marker file so we can detect the dir was actually removed
	// vs left empty.
	if err := os.WriteFile(filepath.Join(d, "docker-compose.yml"), []byte("services: {}\n"), 0o644); err != nil {
		t.Fatalf("write marker for %q: %v", d, err)
	}
}

func listApps(t *testing.T, catalogDir string) []string {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(catalogDir, "Apps"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		t.Fatalf("readdir: %v", err)
	}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			out = append(out, e.Name())
		}
	}
	sort.Strings(out)
	return out
}

func TestPruneOrphanCuratedApps_RemovesOrphans(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "Apps"), 0o755); err != nil {
		t.Fatal(err)
	}
	// Curated set: 4 founding apps. Disk has 4 founders + 3 Umbrel orphans.
	writeManifest(t, dir, "adventurelog", "baikal", "enclosed", "gitingest")
	for _, n := range []string{"adventurelog", "baikal", "enclosed", "gitingest",
		"home-assistant", "jellyfin", "nextcloud"} {
		mkAppDir(t, dir, n)
	}

	kept, removed, err := pruneOrphanCuratedApps(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	wantKept := []string{"adventurelog", "baikal", "enclosed", "gitingest"}
	wantRemoved := []string{"home-assistant", "jellyfin", "nextcloud"}
	sort.Strings(kept)
	sort.Strings(removed)
	if !reflect.DeepEqual(kept, wantKept) {
		t.Errorf("kept: got %v, want %v", kept, wantKept)
	}
	if !reflect.DeepEqual(removed, wantRemoved) {
		t.Errorf("removed: got %v, want %v", removed, wantRemoved)
	}
	// Confirm orphans actually gone on disk.
	got := listApps(t, dir)
	if !reflect.DeepEqual(got, wantKept) {
		t.Errorf("on disk after prune: got %v, want %v", got, wantKept)
	}
}

func TestPruneOrphanCuratedApps_NoManifest_NoOp(t *testing.T) {
	// Defense in depth: if the manifest is missing (old install, never
	// upgraded to v0.7.1, hand-installed catalog), we must NOT wipe
	// anything. Better to leave orphans than to delete an operator's
	// hand-curated set.
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "Apps"), 0o755); err != nil {
		t.Fatal(err)
	}
	for _, n := range []string{"alpha", "beta", "gamma"} {
		mkAppDir(t, dir, n)
	}

	kept, removed, err := pruneOrphanCuratedApps(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(kept) != 0 || len(removed) != 0 {
		t.Errorf("expected noop on missing manifest, got kept=%v removed=%v", kept, removed)
	}
	// All on-disk dirs still present.
	got := listApps(t, dir)
	want := []string{"alpha", "beta", "gamma"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("on disk after noop: got %v, want %v", got, want)
	}
}

func TestPruneOrphanCuratedApps_EmptyManifest_NoOp(t *testing.T) {
	// Empty manifest is ambiguous — could mean "zero curated apps" or
	// "manifest got truncated." Skip rather than risk wiping. The
	// install-time wipe-then-copy (PR #451) is the authoritative path
	// for an actual zero-curated release.
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "Apps"), 0o755); err != nil {
		t.Fatal(err)
	}
	writeManifest(t, dir) // no entries
	for _, n := range []string{"alpha", "beta"} {
		mkAppDir(t, dir, n)
	}

	kept, removed, err := pruneOrphanCuratedApps(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(kept) != 0 || len(removed) != 0 {
		t.Errorf("expected noop on empty manifest, got kept=%v removed=%v", kept, removed)
	}
}

func TestPruneOrphanCuratedApps_ManifestIgnoresCommentsAndBlanks(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "Apps"), 0o755); err != nil {
		t.Fatal(err)
	}
	manifest := "# Generated by package-linux.sh — DO NOT edit by hand\n" +
		"\n" +
		"adventurelog\n" +
		"  baikal  \n" + // leading/trailing whitespace
		"# enclosed (commented out for some reason)\n" +
		"gitingest\n"
	if err := os.WriteFile(filepath.Join(dir, curatedManifestFilename), []byte(manifest), 0o644); err != nil {
		t.Fatal(err)
	}
	for _, n := range []string{"adventurelog", "baikal", "enclosed", "gitingest"} {
		mkAppDir(t, dir, n)
	}

	_, removed, err := pruneOrphanCuratedApps(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// `enclosed` was commented out — treated as not in curated set, so
	// removed.
	want := []string{"enclosed"}
	if !reflect.DeepEqual(removed, want) {
		t.Errorf("removed: got %v, want %v", removed, want)
	}
}

func TestPruneOrphanCuratedApps_MissingAppsDir_NoOp(t *testing.T) {
	dir := t.TempDir()
	writeManifest(t, dir, "adventurelog")
	// No Apps/ dir at all.

	kept, removed, err := pruneOrphanCuratedApps(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(kept) != 0 || len(removed) != 0 {
		t.Errorf("expected noop on missing Apps/, got kept=%v removed=%v", kept, removed)
	}
}

func TestPruneOrphanCuratedApps_PreservesFiles(t *testing.T) {
	// Files (not dirs) under Apps/ are ignored — only directories are
	// considered apps. A stray README.md or .DS_Store shouldn't be
	// touched.
	dir := t.TempDir()
	apps := filepath.Join(dir, "Apps")
	if err := os.MkdirAll(apps, 0o755); err != nil {
		t.Fatal(err)
	}
	writeManifest(t, dir, "adventurelog")
	mkAppDir(t, dir, "adventurelog")
	mkAppDir(t, dir, "orphan-app")
	if err := os.WriteFile(filepath.Join(apps, ".DS_Store"), []byte{}, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(apps, "README.md"), []byte("hi"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, removed, err := pruneOrphanCuratedApps(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !reflect.DeepEqual(removed, []string{"orphan-app"}) {
		t.Errorf("removed: got %v, want [orphan-app]", removed)
	}
	// Non-dir files preserved.
	if _, err := os.Stat(filepath.Join(apps, ".DS_Store")); err != nil {
		t.Errorf(".DS_Store removed unexpectedly: %v", err)
	}
	if _, err := os.Stat(filepath.Join(apps, "README.md")); err != nil {
		t.Errorf("README.md removed unexpectedly: %v", err)
	}
}

func TestMigrateOrphanCuratedApps_NilSafe(t *testing.T) {
	// Defensive: must not panic when AppInfo / ServerInfo not populated.
	savedApp := AppInfo
	savedServer := ServerInfo
	AppInfo = nil
	ServerInfo = nil
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("MigrateOrphanCuratedApps panicked on nil config: %v", r)
		}
		AppInfo = savedApp
		ServerInfo = savedServer
	}()
	MigrateOrphanCuratedApps()
}
