name: passky-server
services:
    server:
        environment:
            ACCOUNT_MAX: 100
            ACCOUNT_MAX_PASSWORDS: 1000
            ACCOUNT_PREMIUM: -1
            ADMIN_PASSWORD: ${APP_PASSWORD}
            ADMIN_USERNAME: admin
            CF_TURNSTILE_SECRET_KEY: 1x0000000000000000000000000000000AA
            CF_TURNSTILE_SITE_KEY: 1x00000000000000000000AA
            DATABASE_ENGINE: sqlite
            DATABASE_FILE: passky
            LIMITER_ADD_YUBIKEY: 10
            LIMITER_CREATE_ACCOUNT: 10
            LIMITER_DELETE_ACCOUNT: 10
            LIMITER_DELETE_PASSWORD: 2
            LIMITER_DELETE_PASSWORDS: 10
            LIMITER_DISABLE_2FA: 10
            LIMITER_EDIT_PASSWORD: 2
            LIMITER_ENABLE_2FA: 10
            LIMITER_ENABLED: "true"
            LIMITER_FORGOT_USERNAME: 60
            LIMITER_GET_INFO: -1
            LIMITER_GET_PASSWORDS: 2
            LIMITER_GET_REPORT: -1
            LIMITER_GET_STATS: -1
            LIMITER_GET_TOKEN: 3
            LIMITER_IMPORT_PASSWORDS: 10
            LIMITER_REMOVE_YUBIKEY: 10
            LIMITER_SAVE_PASSWORD: 2
            LIMITER_UPGRADE_ACCOUNT: 10
            MAIL_ENABLED: "false"
            MYSQL_CACHE_MODE: 0
            MYSQL_DATABASE: passky
            MYSQL_HOST: ""
            MYSQL_PASSWORD: ""
            MYSQL_PORT: 3306
            MYSQL_SSL: "false"
            MYSQL_SSL_CA: /etc/ssl/certs/ca-certificates.crt
            MYSQL_USER: passky
            REDIS_HOST: 127.0.0.1
            REDIS_LOCAL_HOST: 127.0.0.1
            REDIS_LOCAL_PASSWORD: ""
            REDIS_LOCAL_PORT: 6379
            REDIS_PASSWORD: ""
            REDIS_PORT: 6379
            SERVER_CORES: 1
            SERVER_LOCATION: US
            YUBI_CLOUD: https://api.yubico.com/wsapi/2.0/verify
            YUBI_ID: 67857
        image: rabbitcompany/passky-server:8.1.8@sha256:e9bf7b9ecdf4904f1e3893b5968e98cbb61d4984bca1482081df2f59df05fca6
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - /DATA/PowerLabAppData/passky-server/data/passky:/var/www/html/databases
version: "3.7"

x-powerlab:
    store_app_id: passky-server
    title:
        en_us: Passky Server
    tagline:
        en_us: Simple, modern, lightweight, open source and secure password manager
    description:
        en_us: "<h1 align=\"center\">\U0001F512 Passky Server \U0001F512</h1> [](https://github.com/Rabbit-Company/Passky-Server/issues) [](https://github.com/Rabbit-Company/Passky-Server/stargazers) [](https://github.com/Rabbit-Company/Passky-Server/network) [](https://github.com/Rabbit-Company/Passky-Server/blob/main/LICENSE) Download from Official Website Passky Clients * Website * Browser Extension * Desktop Application * Android Application What is Passky? Passky is a simple, modern, lightweight, open source and secure password manager. [](https://www.youtube.com/watch?v=yrk6cHkgVA8 \"Click to watch!\") How Much Does it Cost? Passky is a **free**, open-source password manager that simplifies your digital life. Both the free and premium plans include advanced security features such as two-factor authentication to ensure the safety and security of your sensitive data. While the free plan allows you to store up to 100 passwords, the premium plan offers additional benefits such as the ability to store an unlimited number of passwords. Upgrade to the premium plan to gain access to all of Passky's features and take your password security to the next level. At Passky, we take your security seriously, and we don't compromise on safety when it comes to password management. Sign up now and experience the peace of mind that comes with using Passky. How it Works? Passky uses a combination of advanced encryption methods to ensure the security of your data. Passky is based on a **zero trust architecture** and uses advanced encryption…"
    icon: https://getumbrel.github.io/umbrel-apps-gallery/passky-server/icon.svg
    category: files
    port_map: "5050"
    author: Rabbit Company LLC
    developer: Rabbit Company LLC
    source:
        catalog: umbrel-apps
        upstream_id: passky-server
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 8a60bdaddda5062fa19b2b13a47966de5af986cf
        upstream_path: passky-server/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-12T14:50:20Z"
