package server

import (
	"net/http"
	"testing"
)

// AgentIdentity extracts the JWT subject + loopback flag from the
// HTTP headers an MCP handler receives via req.Extra.Header (the SDK
// already plumbs the original request's headers into every handler
// invocation per shared.go::RequestExtra). Per ADR-0047 this is the
// foundation for both (a) audit dogfood (recorder sees the right
// user) and (b) JWT forwarding to upstream calls via coreproxy.
func TestAgentIdentity_LoopbackWhenNoAuthorizationHeader(t *testing.T) {
	h := http.Header{}
	sub, token, isLoopback := AgentIdentity(h)
	if !isLoopback {
		t.Errorf("isLoopback=false; expected true when no Authorization header")
	}
	if sub != "" {
		t.Errorf("sub=%q; expected empty when no auth header", sub)
	}
	if token != "" {
		t.Errorf("token=%q; expected empty when no auth header", token)
	}
}

// Valid Bearer token → extract sub claim + raw token. Use a hardcoded
// fixture token whose payload decodes to {"username":"alice","id":42}
// (PowerLab JWT shape per user-service/route/v1/user.go).
func TestAgentIdentity_ExtractsSubAndToken(t *testing.T) {
	// Fixture: header={"alg":"ES256","typ":"JWT"}, payload={"username":"alice","id":42,"sub":"alice"}, sig=truncated
	// Generated by hand; the validator runs upstream — this helper
	// only parses the unverified payload to grab `sub` for the audit
	// record + forwarding. The real verification ran at jwt.HTTPJWT
	// BEFORE the handler executes.
	// #nosec G101 -- test fixture, not a real credential
	token := "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaWNlIiwiaWQiOjQyLCJzdWIiOiJhbGljZSJ9.fake_sig"
	h := http.Header{}
	h.Set("Authorization", "Bearer "+token)

	sub, gotToken, isLoopback := AgentIdentity(h)
	if isLoopback {
		t.Errorf("isLoopback=true; expected false when Authorization header is present")
	}
	if sub != "alice" {
		t.Errorf("sub=%q; expected %q (extracted from JWT payload)", sub, "alice")
	}
	if gotToken != token {
		t.Errorf("token mismatch; want the raw JWT for upstream forwarding")
	}
}

// Malformed Bearer (no payload, no dots) — defensive: treat as
// loopback-equivalent rather than panic. We're not the validator;
// the validator already ran upstream. If we get here with garbage
// it's a pre-auth slip and we degrade safely.
func TestAgentIdentity_MalformedBearer(t *testing.T) {
	h := http.Header{}
	h.Set("Authorization", "Bearer not-a-jwt")

	sub, _, _ := AgentIdentity(h)
	if sub != "" {
		t.Errorf("sub=%q; malformed JWT should yield empty sub", sub)
	}
}

// Header present but no Bearer prefix (e.g. Basic auth, or just a
// raw token) — same defensive fallback.
func TestAgentIdentity_NonBearerScheme(t *testing.T) {
	h := http.Header{}
	h.Set("Authorization", "Basic dXNlcjpwYXNz")

	sub, token, isLoopback := AgentIdentity(h)
	if sub != "" || token != "" {
		t.Errorf("non-Bearer scheme should yield empty sub+token; got sub=%q token=%q", sub, token)
	}
	if !isLoopback {
		t.Errorf("non-Bearer should fall back to loopback path (caller will treat as anonymous)")
	}
}
