name: libreddit
services:
    web:
        environment:
            PORT: 7420
        healthcheck:
            disable: true
        image: ceramicwhite/libreddit:0.22.9@sha256:00a133da4ae8eb1b7d3ce9af0ca387e2dd929dc6b490736532b5d998a025c362
        init: true
        ports:
            - 7420:7420
        restart: on-failure
        stop_grace_period: 1m
        user: 1000:1000
version: "3.7"

x-powerlab:
    store_app_id: libreddit
    title:
        en_us: LibReddit
    tagline:
        en_us: An alternative private front-end to Reddit
    icon: https://getumbrel.github.io/umbrel-apps-gallery/libreddit/icon.svg
    category: social
    port_map: "7420"
    author: Spikecodes
    developer: Spikecodes
    main: web
    source:
        catalog: umbrel-apps
        upstream_id: libreddit
        upstream_repo: https://github.com/getumbrel/umbrel-apps.git
        upstream_commit: 7d224ca6c493d2279a49086ed9e7bf45d642d9e6
        upstream_path: libreddit/umbrel-app.yml
        transform_version: "1.0"
        synced_at: "2026-05-18T10:13:42Z"
